import Foundation

// Emits, for every enum value carrying a `(url_token)` option, the spelling it takes in a URL and
// an initializer that reads one back.
//
// The client that writes `?sort=top` and the server that matches on it have to agree, and the only
// way for that to be one fact is for both to read it from the schema. Hand-typed on either side it
// is a copy, and the day they disagree the server answers a default nobody asked for.
//
// A value with no token has no spelling and cannot be sent, which is what keeps a zero sentinel out
// of a query string.
//
// A pure parser over the proto text, like endpoint-gen: swift-protobuf does not surface custom
// options on generated enums, so there is nothing to read at runtime.

struct TokenValue {
  let protoName: String
  let token: String
}

struct TokenEnum {
  let name: String
  let values: [TokenValue]
}

enum GeneratorError: Error, CustomStringConvertible {
  case usage
  case unreadable(String)

  var description: String {
    switch self {
    case .usage:
      return "usage: tokens-gen <input.proto> <output-directory>"
    case .unreadable(let path):
      return "cannot read \(path)"
    }
  }
}

func parse(_ text: String) -> (prefix: String, enums: [TokenEnum]) {
  var prefix = ""
  var enums: [TokenEnum] = []

  var currentEnum: String?
  var currentValues: [TokenValue] = []

  for rawLine in text.split(separator: "\n", omittingEmptySubsequences: false) {
    let line = rawLine.trimmingCharacters(in: .whitespaces)

    if line.hasPrefix("option swift_prefix") {
      if let first = line.firstIndex(of: "\""), let last = line.lastIndex(of: "\""), first < last {
        prefix = String(line[line.index(after: first)..<last])
      }
      continue
    }

    if line.hasPrefix("enum ") {
      currentEnum = line
        .dropFirst("enum ".count)
        .trimmingCharacters(in: CharacterSet(charactersIn: " {"))
      currentValues = []
      continue
    }

    guard let enumName = currentEnum else { continue }

    if line == "}" {
      if currentValues.isEmpty == false {
        enums.append(TokenEnum(name: enumName, values: currentValues))
      }
      currentEnum = nil
      currentValues = []
      continue
    }

    guard line.contains("(url_token)") else { continue }
    guard let equalsIndex = line.firstIndex(of: "=") else { continue }
    let valueName = line[..<equalsIndex].trimmingCharacters(in: .whitespaces)

    // The token is the quoted string in the option.
    let afterOption = line[line.index(after: equalsIndex)...]
    guard let openQuote = afterOption.firstIndex(of: "\"") else { continue }
    let remainder = afterOption[afterOption.index(after: openQuote)...]
    guard let closeQuote = remainder.firstIndex(of: "\"") else { continue }
    let token = String(remainder[..<closeQuote])

    currentValues.append(TokenValue(protoName: valueName, token: token))
  }

  return (prefix, enums)
}

/// `REQUEST_SORT_TOP` in `RequestSort` -> `top`: the case name protoc-gen-swift generates, derived
/// by stripping the enum's own screaming-snake prefix.
func swiftCase(valueName: String, enumName: String) -> String {
  let screamingEnum = screamingSnake(enumName)
  var withoutPrefix = valueName
  if valueName.hasPrefix(screamingEnum + "_") {
    withoutPrefix = String(valueName.dropFirst(screamingEnum.count + 1))
  }
  let words = withoutPrefix.split(separator: "_").map { $0.lowercased() }
  guard let first = words.first else { return withoutPrefix.lowercased() }
  return first + words.dropFirst().map { $0.capitalized }.joined()
}

func screamingSnake(_ camel: String) -> String {
  var out = ""
  for character in camel {
    if character.isUppercase, out.isEmpty == false {
      out.append("_")
    }
    out.append(Character(character.uppercased()))
  }
  return out
}

func render(prefix: String, enums: [TokenEnum], sourceFile: String) -> String {
  var out = """
    // DO NOT EDIT.
    //
    // Generated by tokens-gen from \(sourceFile). Run Scripts/generate.sh.

    """

  for tokenEnum in enums {
    let type = "\(prefix)\(tokenEnum.name)"
    out += """

      extension \(type) {
        /// How this value is spelled in a URL.
        ///
        /// Absent for a value with no declared spelling, which is what makes an unsendable value
        /// impossible to put in a query string rather than merely discouraged.
        public var urlToken: String? {
          switch self {

      """

    for value in tokenEnum.values {
      out += "    case .\(swiftCase(valueName: value.protoName, enumName: tokenEnum.name)): return \"\(value.token)\"\n"
    }

    out += """
          default: return nil
          }
        }

        /// Reads a value back from its spelling. Nil for anything not in the contract, so an
        /// unrecognized token is rejected by the caller rather than silently becoming a default.
        public init?(urlToken: String) {
          switch urlToken {

      """

    for value in tokenEnum.values {
      out += "    case \"\(value.token)\": self = .\(swiftCase(valueName: value.protoName, enumName: tokenEnum.name))\n"
    }

    out += """
          default: return nil
          }
        }
      }

      """
  }

  return out
}

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
  FileHandle.standardError.write(Data((GeneratorError.usage.description + "\n").utf8))
  exit(1)
}

do {
  guard let text = try? String(contentsOfFile: arguments[1], encoding: .utf8) else {
    throw GeneratorError.unreadable(arguments[1])
  }

  let sourceFile = (arguments[1] as NSString).lastPathComponent
  let parsed = parse(text)
  let rendered = render(prefix: parsed.prefix, enums: parsed.enums, sourceFile: sourceFile)

  let outputPath = (arguments[2] as NSString)
    .appendingPathComponent("URLTokens.\((sourceFile as NSString).deletingPathExtension).generated.swift")
  try rendered.write(toFile: outputPath, atomically: true, encoding: .utf8)
  print("tokens-gen: wrote \(outputPath)")
} catch {
  FileHandle.standardError.write(Data(("tokens-gen: \(error)\n").utf8))
  exit(1)
}
