import Foundation

/// One generated Swift file: the do-not-edit banner and every service's tables in it.
struct EndpointTableFile {
  let sourceFileName: String
  let services: [EmittedService]

  var swiftSource: String {
    var out = """
      // DO NOT EDIT.
      //
      // Generated by endpoint-gen from \(sourceFileName). Run Scripts/generate.sh.

      """
    for service in services {
      out += service.swiftSource
    }
    return out
  }
}
