import Foundation

// Emits the endpoint table for every service in a .proto file: the path an rpc is
// called at, and the audience it declared.
//
// It exists so no consumer hand-writes a path. A string like
// "/differentrequests.v1.RequestsService/ListRequests" typed into a client is a copy
// of the service definition that nothing checks, and the server matching on its own
// hand-typed copy is a second one. Both come from here instead.
//
// A pure parser over the proto text, taking no dependency on protoc or
// swift-protobuf: swift-protobuf generates no service code at all, so there is no
// descriptor to read at this stage of the build. Same shape as backlog-proto's
// generators.

struct Method {
  let name: String
  let audience: String
}

struct Service {
  let name: String
  let methods: [Method]
}

enum GeneratorError: Error, CustomStringConvertible {
  case usage
  case unreadable(String)
  case noPackage(String)
  case methodWithoutAudience(service: String, method: String)

  var description: String {
    switch self {
    case .usage:
      return "usage: endpoint-gen <input.proto> <output-directory>"
    case .unreadable(let path):
      return "cannot read \(path)"
    case .noPackage(let path):
      return "\(path) declares no package; the rpc path is built from it"
    case .methodWithoutAudience(let service, let method):
      // The whole point of the audience option is that forgetting it cannot leave a
      // route silently open, so this is fatal rather than defaulted.
      return "\(service).\(method) declares no (audience) option"
    }
  }
}

func parse(_ text: String, path: String) throws -> (package: String, services: [Service]) {
  var package = ""
  var services: [Service] = []

  var currentService: String?
  var currentMethods: [Method] = []
  var pendingMethod: String?

  // Depth relative to the enclosing `service` block: 1 inside the service, 2 inside an
  // rpc's own braces. Tracked rather than matching a bare `}`, because every rpc that
  // carries an option closes with one and that is not the end of the service.
  var depth = 0

  for rawLine in text.split(separator: "\n", omittingEmptySubsequences: false) {
    let line = rawLine.trimmingCharacters(in: .whitespaces)

    if depth == 0 {
      if line.hasPrefix("package ") {
        package = line
          .dropFirst("package ".count)
          .trimmingCharacters(in: CharacterSet(charactersIn: " ;"))
      } else if line.hasPrefix("service ") {
        currentService = line
          .dropFirst("service ".count)
          .trimmingCharacters(in: CharacterSet(charactersIn: " {"))
        currentMethods = []
        depth = 1
      }
      continue
    }

    guard let service = currentService else { continue }

    if line.hasPrefix("rpc ") {
      let afterKeyword = line.dropFirst("rpc ".count)
      if let parenIndex = afterKeyword.firstIndex(of: "(") {
        pendingMethod = afterKeyword[..<parenIndex].trimmingCharacters(in: .whitespaces)
      }
    } else if line.hasPrefix("option (audience)"), let method = pendingMethod {
      if let equalsIndex = line.firstIndex(of: "=") {
        let audience = line[line.index(after: equalsIndex)...]
          .trimmingCharacters(in: CharacterSet(charactersIn: " ;"))
        currentMethods.append(Method(name: method, audience: audience))
        pendingMethod = nil
      }
    }

    let depthBefore = depth
    depth += line.filter { $0 == "{" }.count
    depth -= line.filter { $0 == "}" }.count

    // An rpc block just closed. If it never declared an audience, that is fatal: the
    // option exists so a forgotten one cannot leave a route open.
    if depthBefore == 2, depth == 1, let method = pendingMethod {
      throw GeneratorError.methodWithoutAudience(service: service, method: method)
    }

    if depth == 0 {
      if !currentMethods.isEmpty {
        services.append(Service(name: service, methods: currentMethods))
      }
      currentService = nil
      currentMethods = []
    }
  }

  if package.isEmpty {
    throw GeneratorError.noPackage(path)
  }

  return (package, services)
}

func swiftCase(_ methodName: String) -> String {
  guard let first = methodName.first else { return methodName }
  return first.lowercased() + methodName.dropFirst()
}

func render(package: String, services: [Service], sourceFile: String) -> String {
  var out = """
    // DO NOT EDIT.
    //
    // Generated by endpoint-gen from \(sourceFile). Run Scripts/generate.sh.

    """

  for service in services {
    out += """

      /// Every rpc on `\(package).\(service.name)`, with the path it is called at and the
      /// credential it requires.
      ///
      /// The path is not a choice and is not written anywhere by hand: every rpc is a POST
      /// to `/<package>.<Service>/<Method>` carrying its request message as a protobuf
      /// binary body.
      public enum \(service.name)Method: String, Sendable, CaseIterable {

      """

    for method in service.methods {
      out += "  case \(swiftCase(method.name)) = \"/\(package).\(service.name)/\(method.name)\"\n"
    }

    out += """

        /// The minimum credential a caller must present. A server rejects anything weaker;
        /// a client that has not authenticated knows before calling.
        public var audience: Audience {
          switch self {

      """

    for method in service.methods {
      out += "    case .\(swiftCase(method.name)): return .\(swiftEnumCase(method.audience))\n"
    }

    out += """
          }
        }

        /// The path this rpc is called at, relative to the API base URL.
        public var path: String { rawValue }
      }

      """
  }

  return out
}

// AUDIENCE_END_USER -> endUser, matching how protoc-gen-swift names the case it
// generates for that value. Derived rather than mapped, so a new audience value needs
// no change here.
func swiftEnumCase(_ protoValue: String) -> String {
  let withoutPrefix = protoValue.hasPrefix("AUDIENCE_")
    ? String(protoValue.dropFirst("AUDIENCE_".count))
    : protoValue
  let words = withoutPrefix.split(separator: "_").map { $0.lowercased() }
  guard let first = words.first else { return withoutPrefix.lowercased() }
  return first + words.dropFirst().map { $0.capitalized }.joined()
}

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
  FileHandle.standardError.write(Data((GeneratorError.usage.description + "\n").utf8))
  exit(1)
}

let inputPath = arguments[1]
let outputDirectory = arguments[2]

do {
  guard let text = try? String(contentsOfFile: inputPath, encoding: .utf8) else {
    throw GeneratorError.unreadable(inputPath)
  }

  let sourceFile = (inputPath as NSString).lastPathComponent
  let parsed = try parse(text, path: inputPath)
  let rendered = render(
    package: parsed.package,
    services: parsed.services,
    sourceFile: sourceFile
  )

  let outputPath = (outputDirectory as NSString)
    .appendingPathComponent("ServiceEndpoints.generated.swift")
  try rendered.write(toFile: outputPath, atomically: true, encoding: .utf8)
  print("endpoint-gen: wrote \(outputPath)")
} catch {
  FileHandle.standardError.write(Data(("endpoint-gen: \(error)\n").utf8))
  exit(1)
}
