/// One Swift file's worth of vocabulary: a proto enum resolved to a name and cases
/// that carry their tokens.
struct EmittedEnum {
  let name: String
  let documentation: [String]
  let cases: [EmittedCase]
  let protoFileName: String

  var fileName: String {
    "\(name).swift"
  }

  var swiftSource: String {
    var lines: [String] = []
    lines.append(contentsOf: documentation)
    lines.append(
      "/// Generated by vocab-gen from \(protoFileName). Edit the proto, not this file."
    )
    lines.append("/// The token is the contract; the case name is convenience.")
    lines.append("public enum \(name): String, CaseIterable, Sendable {")
    for emitted in cases {
      for line in emitted.documentation {
        lines.append("  \(line)")
      }
      lines.append("  case \(emitted.name) = \(emitted.stringLiteral)")
    }
    lines.append("}")
    return lines.joined(separator: "\n") + "\n"
  }
}
