import Foundation

/// One generated Swift file: the do-not-edit banner and every table in it.
struct FieldTableFile {
  let sourceFileName: String
  let tables: [EmittedFieldTable]

  var swiftSource: String {
    var out = """
      // DO NOT EDIT.
      //
      // Generated by fields-gen from \(sourceFileName). Run Scripts/generate.sh.

      """
    for table in tables {
      out += table.swiftSource
    }
    return out
  }
}
