import Foundation

/// One generated Swift file: the do-not-edit banner, every enum's spellings in it, and what its
/// values say about boards.
struct SpellingFile {
  let sourceFileName: String
  let spelledEnums: [EmittedTokenEnum]

  /// The enums whose values say whether a board shows them.
  let boardStates: [EmittedBoardStates]

  var swiftSource: String {
    var out = """
      // DO NOT EDIT.
      //
      // Generated by tokens-gen from \(sourceFileName). Run Scripts/generate.sh.

      """
    for spelled in spelledEnums {
      out += spelled.swiftSource
    }
    for states in boardStates {
      out += states.swiftSource
    }
    return out
  }
}
