import Foundation

/// One generated Swift file: the do-not-edit banner and every enum's spellings in it.
struct SpellingFile {
  let sourceFileName: String
  let spelledEnums: [EmittedTokenEnum]

  var swiftSource: String {
    var out = """
      // DO NOT EDIT.
      //
      // Generated by tokens-gen from \(sourceFileName). Run Scripts/generate.sh.

      """
    for spelled in spelledEnums {
      out += spelled.swiftSource
    }
    return out
  }
}
