/// The scheme prefixing a credential in an `Authorization` header.
///
/// A caller writes the scheme into the value and the server strips it back off, so a
/// change here is a change both sides make together.
/// Generated by vocab-gen from differentrequests_vocabulary.proto. Edit the proto, not this file.
/// The token is the contract; the case name is convenience.
public enum DRAuthorizationScheme: String, CaseIterable, Sendable {
  case bearer = "Bearer"
}
