/// Header names on requests this API sends or receives.
///
/// Both were literals in two repositories: the SDK wrote them and the server matched
/// on them, and nothing failed loudly if they stopped agreeing — the server would
/// simply stop seeing a credential the client believed it had sent.
/// Generated by vocab-gen from differentrequests_vocabulary.proto. Edit the proto, not this file.
/// The token is the contract; the case name is convenience.
public enum DRHTTPHeaderName: String, CaseIterable, Sendable {
  /// The header an app key is presented in, on every rpc without exception. Names
  /// the tenant's app and nobody within it.
  case appKey = "X-App-Key"
  /// The header an end-user session token is presented in, under the bearer scheme.
  case authorization = "Authorization"
  case contentType = "Content-Type"
  /// What a caller will accept back. Every response on this API is a serialized
  /// message, so this is sent on every request and never varies.
  case accept = "Accept"
  /// Which build of the SDK is calling, and on what. Sent on every rpc.
  ///
  /// Shaped `differentrequests-swift/<version> (<platform> <os version>)`. It names the
  /// library, never the person or the device: no identifier, nothing that survives an
  /// install, nothing a second request could be joined to a first by.
  ///
  /// It exists because a released SDK carries its base URL in the binary, so two
  /// hostnames are live in the wild at once and a failing request cannot otherwise say
  /// which build sent it. Answering "you are on 0.4.2, which dials the old name" is the
  /// difference between a support thread and a sentence.
  case client = "X-DR-Client"
}
