/// Header names on requests this API sends or receives.
///
/// Both were literals in two repositories: the SDK wrote them and the server matched
/// on them, and nothing failed loudly if they stopped agreeing — the server would
/// simply stop seeing a credential the client believed it had sent.
/// Generated by vocab-gen from differentrequests_vocabulary.proto. Edit the proto, not this file.
/// The token is the contract; the case name is convenience.
public enum DRHTTPHeaderName: String, CaseIterable, Sendable {
  /// The header an app key is presented in, on every rpc without exception. Names
  /// the tenant's app and nobody within it.
  case appKey = "X-App-Key"
  /// The header an end-user session token is presented in, under the bearer scheme.
  case authorization = "Authorization"
  case contentType = "Content-Type"
}
