/// The media type every request and response body carries, in both directions.
///
/// Every payload on this API is a serialized message, a failure included — which is
/// why there is one media type here and not one per direction.
/// Generated by vocab-gen from differentrequests_vocabulary.proto. Edit the proto, not this file.
/// The token is the contract; the case name is convenience.
public enum DRMediaType: String, CaseIterable, Sendable {
  case protobuf = "application/x-protobuf"
}
