// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: differentrequests_options.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Route metadata attached to an rpc: the verb and path it is served at, and the
/// credential it requires.
///
/// endpoint-gen reads these and emits one endpoint table, which both the server's
/// router and the SDK's client are built from. Neither side writes a path, so
/// neither can spell one the other does not serve.
///
/// The audience is here because it is the one thing HTTP cannot state, and getting
/// it wrong is what leaks one tenant's board into another's app.
///
/// Three scalar options rather than one `Route` message at 51240, which is retired.
/// A message-typed option can only be read by decoding it, and decoding needs the
/// generated Swift for this file — which would make the generator that produces
/// that Swift depend on its own output. Scalars are read as the numbers they are
/// and their names resolved through the descriptor, so the generator needs no
/// generated type at all.
/// A surface a tenant's plan may or may not include.
///
/// Named on the rpc it gates rather than checked inside the handler that serves it.
/// A guard written in a handler is a fact about the product kept in the one place
/// nothing else looks: an rpc added to a paid surface without one answers for every
/// tenant, and nothing says so until somebody notices they are getting it free.
///
/// There is no value for a surface every plan includes. An rpc that names no gate
/// is not gated, which is the same statement made by saying nothing.
public enum DRPlanSurface: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case roadmap // = 1
  case changelog // = 2

  /// Not a paid anchor: comments are free on every plan and absent when the tenant
  /// has chosen not to moderate a discussion. It is here because the gate is the
  /// same gate — an AppConfig flag the server answers against before a handler
  /// runs — and a second mechanism for "this app does not have that" would be a
  /// second place to forget one.
  case comments // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .roadmap
    case 2: self = .changelog
    case 3: self = .comments
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .roadmap: return 1
    case .changelog: return 2
    case .comments: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRPlanSurface] = [
    .unspecified,
    .roadmap,
    .changelog,
    .comments,
  ]

}

/// Which allowance a call spends before it is answered.
///
/// Declared on the rpc because what a call costs is a fact about the rpc, not about
/// its verb. Read off the verb, every non-GET was a write, and signing somebody in
/// spent the same per-app allowance as a vote — so a flood of sign-ins refused the
/// people voting.
public enum DRAllowance: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never valid on an rpc. An rpc that does not say what it costs is a generator
  /// error rather than a call nothing counts.
  case unspecified // = 0

  /// Counted against nothing: a read.
  case uncounted // = 1

  /// A change made by an app or by a person in it, counted against the person and
  /// their app.
  case write // = 2

  /// Minting a session, counted against the calling address and the app, and
  /// against the app's new people when it names somebody for the first time.
  case signIn // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .uncounted
    case 2: self = .write
    case 3: self = .signIn
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .uncounted: return 1
    case .write: return 2
    case .signIn: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRAllowance] = [
    .unspecified,
    .uncounted,
    .write,
    .signIn,
  ]

}

/// The *minimum* credential a caller must present. Every rpc names exactly one;
/// there is no "any" and no default, so an rpc that forgets to say is a generator
/// error rather than an open endpoint.
///
/// Minimum, not exact: an end-user session is always accompanied by an app key, so
/// an rpc marked APP_KEY also serves a session caller — and populates the
/// viewer-relative fields it would otherwise omit. The reverse never holds. An rpc
/// marked END_USER rejects a bare app key.
///
/// There are deliberately no console or platform-admin values. Those surfaces are
/// server-rendered HTML in a private repository and have no rpcs to mark, so a
/// value for them would name a caller that does not exist.
public enum DRAudience: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never valid on an rpc. Present because proto3 requires a zero value, and an
  /// unset audience must fail loudly rather than resolve to the weakest one.
  case unspecified // = 0

  /// `X-App-Key: dr_<hex>` alone. Identifies the tenant's app but nobody within
  /// it, so these rpcs may not read or write anything user-scoped.
  case appKey // = 1

  /// App key plus an end-user session token issued by CreateSession. Everything an
  /// SDK caller does on behalf of a person: submit, vote, follow, comment, read
  /// their inbox.
  case endUser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .appKey
    case 2: self = .endUser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .appKey: return 1
    case .endUser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRAudience] = [
    .unspecified,
    .appKey,
    .endUser,
  ]

}

/// The verb an rpc is served at.
///
/// Each value spells itself, because a client has to put the verb on the wire and
/// the spelling is what goes there. Spelled in Swift instead, it was a switch that
/// mapped four values to four strings and answered GET for the two it could not
/// map — so an rpc whose route was incomplete would have been sent as a read.
///
/// HTTP_METHOD_UNSPECIFIED carries no spelling. There is nothing to send for it,
/// and a value with no spelling cannot be sent rather than being sent as something
/// else.
public enum DRHttpMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case get // = 1
  case post // = 2
  case put // = 3
  case delete // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .get
    case 2: self = .post
    case 3: self = .put
    case 4: self = .delete
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .get: return 1
    case .post: return 2
    case .put: return 3
    case .delete: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRHttpMethod] = [
    .unspecified,
    .get,
    .post,
    .put,
    .delete,
  ]

}

// MARK: - Extension support defined in differentrequests_options.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  public var DRurlToken: String {
    get {return getExtensionValue(ext: DRExtensions_url_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_url_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_url_token`
  /// has been explicitly set.
  public var hasDRurlToken: Bool {
    return hasExtensionValue(ext: DRExtensions_url_token)
  }
  /// Clears the value of extension `DRExtensions_url_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRurlToken() {
    clearExtensionValue(ext: DRExtensions_url_token)
  }

  public var DRshownOnABoard: Bool {
    get {return getExtensionValue(ext: DRExtensions_shown_on_a_board) ?? false}
    set {setExtensionValue(ext: DRExtensions_shown_on_a_board, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_shown_on_a_board`
  /// has been explicitly set.
  public var hasDRshownOnABoard: Bool {
    return hasExtensionValue(ext: DRExtensions_shown_on_a_board)
  }
  /// Clears the value of extension `DRExtensions_shown_on_a_board`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRshownOnABoard() {
    clearExtensionValue(ext: DRExtensions_shown_on_a_board)
  }

  public var DRtoken: String {
    get {return getExtensionValue(ext: DRExtensions_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_token`
  /// has been explicitly set.
  public var hasDRtoken: Bool {
    return hasExtensionValue(ext: DRExtensions_token)
  }
  /// Clears the value of extension `DRExtensions_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRtoken() {
    clearExtensionValue(ext: DRExtensions_token)
  }

  public var DRlabel: String {
    get {return getExtensionValue(ext: DRExtensions_label) ?? String()}
    set {setExtensionValue(ext: DRExtensions_label, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_label`
  /// has been explicitly set.
  public var hasDRlabel: Bool {
    return hasExtensionValue(ext: DRExtensions_label)
  }
  /// Clears the value of extension `DRExtensions_label`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRlabel() {
    clearExtensionValue(ext: DRExtensions_label)
  }
}

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  public var DRgates: DRPlanSurface {
    get {return getExtensionValue(ext: DRExtensions_gates) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_gates, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_gates`
  /// has been explicitly set.
  public var hasDRgates: Bool {
    return hasExtensionValue(ext: DRExtensions_gates)
  }
  /// Clears the value of extension `DRExtensions_gates`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRgates() {
    clearExtensionValue(ext: DRExtensions_gates)
  }

  /// The longest this text may be, in characters, counted the way a person counts.
  ///
  /// Declared on the field because both sides need the same number for different
  /// reasons: the server refuses anything longer, and the SDK stops somebody at the
  /// keyboard before they lose what they wrote. Written in each repository instead,
  /// it is one limit with two numbers, and the day they differ a person is refused
  /// for a length their composer said was fine.
  ///
  /// Absent means unbounded by the contract. The 64 KB body cap still stands behind
  /// every field and bounds what is read at all.
  public var DRmaxCharacters: UInt32 {
    get {return getExtensionValue(ext: DRExtensions_max_characters) ?? 0}
    set {setExtensionValue(ext: DRExtensions_max_characters, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_max_characters`
  /// has been explicitly set.
  public var hasDRmaxCharacters: Bool {
    return hasExtensionValue(ext: DRExtensions_max_characters)
  }
  /// Clears the value of extension `DRExtensions_max_characters`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRmaxCharacters() {
    clearExtensionValue(ext: DRExtensions_max_characters)
  }
}

extension SwiftProtobuf.Google_Protobuf_MethodOptions {

  public var DRrouteMethod: DRHttpMethod {
    get {return getExtensionValue(ext: DRExtensions_route_method) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_route_method, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_method`
  /// has been explicitly set.
  public var hasDRrouteMethod: Bool {
    return hasExtensionValue(ext: DRExtensions_route_method)
  }
  /// Clears the value of extension `DRExtensions_route_method`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRrouteMethod() {
    clearExtensionValue(ext: DRExtensions_route_method)
  }

  /// Path template relative to the API root, with `{brace}` parameters —
  /// `/requests/{requestId}/comments`. A parameter name matches the field in the
  /// rpc's request message that supplies it, which is what lets the generator bind
  /// it without a second mapping to keep in sync.
  public var DRroutePath: String {
    get {return getExtensionValue(ext: DRExtensions_route_path) ?? String()}
    set {setExtensionValue(ext: DRExtensions_route_path, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_path`
  /// has been explicitly set.
  public var hasDRroutePath: Bool {
    return hasExtensionValue(ext: DRExtensions_route_path)
  }
  /// Clears the value of extension `DRExtensions_route_path`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRroutePath() {
    clearExtensionValue(ext: DRExtensions_route_path)
  }

  public var DRrouteAudience: DRAudience {
    get {return getExtensionValue(ext: DRExtensions_route_audience) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_route_audience, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_audience`
  /// has been explicitly set.
  public var hasDRrouteAudience: Bool {
    return hasExtensionValue(ext: DRExtensions_route_audience)
  }
  /// Clears the value of extension `DRExtensions_route_audience`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRrouteAudience() {
    clearExtensionValue(ext: DRExtensions_route_audience)
  }

  /// The surface a tenant's plan must include for this rpc to answer. Absent on an
  /// rpc every plan includes.
  public var DRplanGate: DRPlanSurface {
    get {return getExtensionValue(ext: DRExtensions_plan_gate) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_plan_gate, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_plan_gate`
  /// has been explicitly set.
  public var hasDRplanGate: Bool {
    return hasExtensionValue(ext: DRExtensions_plan_gate)
  }
  /// Clears the value of extension `DRExtensions_plan_gate`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRplanGate() {
    clearExtensionValue(ext: DRExtensions_plan_gate)
  }

  /// What one call to this rpc is counted against. Every rpc names exactly one.
  public var DRrouteAllowance: DRAllowance {
    get {return getExtensionValue(ext: DRExtensions_route_allowance) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_route_allowance, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_allowance`
  /// has been explicitly set.
  public var hasDRrouteAllowance: Bool {
    return hasExtensionValue(ext: DRExtensions_route_allowance)
  }
  /// Clears the value of extension `DRExtensions_route_allowance`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRrouteAllowance() {
    clearExtensionValue(ext: DRExtensions_route_allowance)
  }

}

// MARK: - File's ExtensionMap: DRDifferentrequestsOptions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let DRDifferentrequestsOptions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  DRExtensions_route_method,
  DRExtensions_route_path,
  DRExtensions_route_audience,
  DRExtensions_plan_gate,
  DRExtensions_route_allowance,
  DRExtensions_gates,
  DRExtensions_max_characters,
  DRExtensions_url_token,
  DRExtensions_shown_on_a_board,
  DRExtensions_token,
  DRExtensions_label
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let DRExtensions_route_method = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRHttpMethod>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51243,
  fieldName: "differentrequests.v1.route_method"
)

/// Path template relative to the API root, with `{brace}` parameters —
/// `/requests/{requestId}/comments`. A parameter name matches the field in the
/// rpc's request message that supplies it, which is what lets the generator bind
/// it without a second mapping to keep in sync.
public let DRExtensions_route_path = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51244,
  fieldName: "differentrequests.v1.route_path"
)

public let DRExtensions_route_audience = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRAudience>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51245,
  fieldName: "differentrequests.v1.route_audience"
)

/// The surface a tenant's plan must include for this rpc to answer. Absent on an
/// rpc every plan includes.
public let DRExtensions_plan_gate = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRPlanSurface>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51246,
  fieldName: "differentrequests.v1.plan_gate"
)

/// What one call to this rpc is counted against. Every rpc names exactly one.
public let DRExtensions_route_allowance = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRAllowance>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51251,
  fieldName: "differentrequests.v1.route_allowance"
)

public let DRExtensions_gates = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRPlanSurface>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 51247,
  fieldName: "differentrequests.v1.gates"
)

/// The longest this text may be, in characters, counted the way a person counts.
///
/// Declared on the field because both sides need the same number for different
/// reasons: the server refuses anything longer, and the SDK stops somebody at the
/// keyboard before they lose what they wrote. Written in each repository instead,
/// it is one limit with two numbers, and the day they differ a person is refused
/// for a length their composer said was fine.
///
/// Absent means unbounded by the contract. The 64 KB body cap still stands behind
/// every field and bounds what is read at all.
public let DRExtensions_max_characters = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufUInt32>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 51249,
  fieldName: "differentrequests.v1.max_characters"
)

public let DRExtensions_url_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51241,
  fieldName: "differentrequests.v1.url_token"
)

public let DRExtensions_shown_on_a_board = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufBool>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51250,
  fieldName: "differentrequests.v1.shown_on_a_board"
)

public let DRExtensions_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51242,
  fieldName: "differentrequests.v1.token"
)

public let DRExtensions_label = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51248,
  fieldName: "differentrequests.v1.label"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DRPlanSurface: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLAN_SURFACE_UNSPECIFIED\0\u{1}PLAN_SURFACE_ROADMAP\0\u{1}PLAN_SURFACE_CHANGELOG\0\u{1}PLAN_SURFACE_COMMENTS\0")
}

extension DRAllowance: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ALLOWANCE_UNSPECIFIED\0\u{1}ALLOWANCE_UNCOUNTED\0\u{1}ALLOWANCE_WRITE\0\u{1}ALLOWANCE_SIGN_IN\0")
}

extension DRAudience: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIENCE_UNSPECIFIED\0\u{1}AUDIENCE_APP_KEY\0\u{1}AUDIENCE_END_USER\0")
}

extension DRHttpMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HTTP_METHOD_UNSPECIFIED\0\u{1}HTTP_METHOD_GET\0\u{1}HTTP_METHOD_POST\0\u{1}HTTP_METHOD_PUT\0\u{1}HTTP_METHOD_DELETE\0")
}
