// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: differentrequests_options.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The *minimum* credential a caller must present. Every rpc names exactly one;
/// there is no "any" and no default, so an rpc that forgets to say is a generator
/// error rather than an open endpoint.
///
/// Minimum, not exact: an end-user session is always accompanied by an app key, so
/// an rpc marked APP_KEY also serves a session caller — and populates the
/// viewer-relative fields it would otherwise omit. The reverse never holds. An rpc
/// marked END_USER rejects a bare app key.
///
/// There are deliberately no console or platform-admin values. Those surfaces are
/// server-rendered HTML in a private repository and have no rpcs to mark, so a
/// value for them would name a caller that does not exist. Add one when there is
/// something to attach it to.
public enum Audience: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never valid on an rpc. Present because proto3 requires a zero value, and an
  /// unset audience must fail loudly rather than resolve to the weakest one.
  case unspecified // = 0

  /// `X-App-Key: dr_<hex>` alone. Identifies the tenant's app but nobody within
  /// it, so these rpcs may not read or write anything user-scoped.
  case appKey // = 1

  /// App key plus an end-user session token issued by CreateSession. Everything an
  /// SDK caller does on behalf of a person: submit, vote, follow, comment, read
  /// their inbox.
  case endUser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .appKey
    case 2: self = .endUser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .appKey: return 1
    case .endUser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Audience] = [
    .unspecified,
    .appKey,
    .endUser,
  ]

}

// MARK: - Extension support defined in differentrequests_options.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_MethodOptions {

  public var audience: Audience {
    get {return getExtensionValue(ext: Extensions_audience) ?? .unspecified}
    set {setExtensionValue(ext: Extensions_audience, value: newValue)}
  }
  /// Returns true if extension `Extensions_audience`
  /// has been explicitly set.
  public var hasAudience: Bool {
    return hasExtensionValue(ext: Extensions_audience)
  }
  /// Clears the value of extension `Extensions_audience`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearAudience() {
    clearExtensionValue(ext: Extensions_audience)
  }

}

// MARK: - File's ExtensionMap: DifferentrequestsOptions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let DifferentrequestsOptions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Extensions_audience
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let Extensions_audience = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<Audience>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51240,
  fieldName: "differentrequests.v1.audience"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Audience: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIENCE_UNSPECIFIED\0\u{1}AUDIENCE_APP_KEY\0\u{1}AUDIENCE_END_USER\0")
}
