// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: differentrequests_domain.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// What an app is entitled to. Two tiers, deliberately: the intermediate tiers
/// tracked previously described a product with no buyers.
public enum DRPlan: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Spelled because an operator names a plan on the command line when provisioning
  /// an app. A value with no spelling cannot be named, which is what keeps the
  /// zero sentinel off the console.
  case free // = 1
  case pro // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .free
    case 2: self = .pro
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .free: return 1
    case .pro: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRPlan] = [
    .unspecified,
    .free,
    .pro,
  ]

}

/// Which kind of state a request is in, as a tag with nothing attached.
///
/// This is what a caller *filters* by and what a roadmap groups by:
/// `?statuses=open,planned` names kinds, not the things inside them. Where a
/// request's own state lives — and what that state carries — is
/// `FeatureRequest.state`.
///
/// Six kinds, each with an action attached. A state nobody acts on is a state
/// that fills up: "under review" is what an untriaged board looks like, and OPEN
/// already says that honestly.
public enum DRRequestStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Submitted, not yet triaged. What every request starts as, and the queue a
  /// triager works through.
  case `open` // = 1

  /// Accepted, not started.
  case planned // = 2
  case inProgress // = 3

  /// Built and released. Terminal.
  case shipped // = 4

  /// Refused, with a reason the author can read. Terminal. A decline with no
  /// reason reads as being ignored, so `decline` below is required in this state.
  case declined // = 5

  /// The same ask, already on the board. Its votes move to the request it
  /// duplicates, which is the whole point of saying so rather than declining it.
  /// `duplicate_of_request_id` is required in this state and meaningless in every
  /// other. A duplicate leaves the board but keeps answering on its own detail
  /// route, because someone holding a link to it should be told where their vote
  /// went rather than shown a 404.
  case duplicate // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .open
    case 2: self = .planned
    case 3: self = .inProgress
    case 4: self = .shipped
    case 5: self = .declined
    case 6: self = .duplicate
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .open: return 1
    case .planned: return 2
    case .inProgress: return 3
    case .shipped: return 4
    case .declined: return 5
    case .duplicate: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRRequestStatus] = [
    .unspecified,
    .open,
    .planned,
    .inProgress,
    .shipped,
    .declined,
    .duplicate,
  ]

}

/// Who wrote a comment, in the sense that decides how it is presented.
///
/// An official reply has to be visibly official. Rendering the developer's answer
/// identically to another user's guess is how a board loses its authority.
public enum DRCommentAuthorRole: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// An end user of the host app.
  case user // = 1

  /// A console operator for this tenant, speaking for the product.
  case team // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .user
    case 2: self = .team
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .user: return 1
    case .team: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRCommentAuthorRole] = [
    .unspecified,
    .user,
    .team,
  ]

}

/// Which APNs environment a device token was minted in. A sandbox token pushed to
/// production fails per-token with no useful error, so the client states it.
public enum DRPushEnvironment: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case sandbox // = 1
  case production // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .sandbox
    case 2: self = .production
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .sandbox: return 1
    case .production: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRPushEnvironment] = [
    .unspecified,
    .sandbox,
    .production,
  ]

}

/// One board, belonging to one tenant, embedded in one iOS app.
///
/// The unit of isolation. Every request, user, vote, and comment below is scoped
/// to an app, and an app key grants access to exactly one — so "which app is
/// this?" is answered by the credential, never by a caller-supplied id. Where an
/// app_id appears on a message below it is describing what the server resolved,
/// not accepting what the client claimed.
public struct DRApp: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var tenantID: String = String()

  public var name: String = String()

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  /// What this app is entitled to, and the only thing GetConfig consults. An app
  /// is both the unit of isolation and the unit of purchase, so both questions an
  /// app key answers — which board, and which surfaces — are answered by the row
  /// the key already resolves to.
  public var plan: DRPlan = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// A person inside a host app, identified without ever signing up.
///
/// The host app already knows who its users are; making them create a second
/// account to ask for a feature is how boards end up empty. So the host app
/// hands us its own stable identifier and we mint a session against it.
public struct DREndUser: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  /// The host app's own identifier for this person, unique within the app. The
  /// dedupe key: the same external_id on a new device is the same person, which
  /// is what lets someone keep their vote history after a reinstall.
  ///
  /// Chosen by the host developer, so it must be treated as untrusted input and
  /// never rendered without escaping.
  public var externalID: String = String()

  /// Both optional, and both only ever supplied by the host app. Absent when the
  /// developer chooses not to share them — the board works without either, and a
  /// request from someone with no name renders as anonymous rather than failing.
  public var email: String = String()

  public var displayName: String = String()

  /// Arbitrary host-app attributes (plan, cohort, install date) carried so a
  /// triager can see who is asking. Untrusted, unindexed, and never used for
  /// authorization.
  public var traits: Dictionary<String,String> = [:]

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// The author of a request or comment, denormalized onto what embeds it.
///
/// A board renders 25 requests; resolving each author separately would be 25
/// extra reads to render a name. Carrying the name here is not a cache — the
/// display name at write time is what the reader should see.
public struct DRUserRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var displayName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A reusable reason a tenant declines things, defined once in the console.
///
/// An entity rather than an enum because the honest reasons are per-product
/// ("outside our platform's capabilities", "conflicts with our roadmap") and a
/// closed set here would force every tenant into ours. Reusable because a
/// triager clearing twenty requests will not write twenty explanations, and
/// declining silently is worse than declining bluntly.
public struct DRDeclineReason: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var appID: String = String()

  /// Shown to end users on every request declined for this reason.
  public var label: String = String()

  /// Optional longer explanation, shown on the request detail.
  public var description_p: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Why one specific request was declined.
public struct DRRequestDecline: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reason: DRDeclineReason {
    get {return _reason ?? DRDeclineReason()}
    set {_reason = newValue}
  }
  /// Returns true if `reason` has been explicitly set.
  public var hasReason: Bool {return self._reason != nil}
  /// Clears the value of `reason`. Subsequent reads from it will return its default value.
  public mutating func clearReason() {self._reason = nil}

  /// Optional free text for this request specifically, in addition to the
  /// reason's own copy. Author-visible: written by an operator for the person who
  /// asked.
  public var note: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reason: DRDeclineReason? = nil
}

/// The three states that are the answer and nothing else. Empty because there is
/// nothing further to say about them, and a message rather than a bare arm
/// because a `oneof` arm takes a type — which is also where a state that later
/// earns a field puts it, without any client having to learn a new one.
public struct DRRequestOpen: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DRRequestPlanned: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DRRequestInProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Built and released.
public struct DRRequestShipped: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The same ask as another request, which now carries this one's votes.
public struct DRRequestDuplicate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required by this shape rather than by a comment, so a duplicate that names
  /// nowhere cannot be written. A duplicate keeps answering on its own detail
  /// route so somebody holding a link is told where their vote went.
  public var duplicateOfRequestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The calling end user's own relationship to a request.
///
/// Separate from the counts because these two fields are the entire difference
/// between a board that feels like a form and one that feels like a room: the
/// vote button has to already know it has been pressed.
public struct DRViewerState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Named `voted` rather than `has_voted`: protoc-gen-swift reserves `has<Field>` for message
  /// presence, so a bool called has_voted generates as `hasVoted_p` and that suffix would show up
  /// at every call site in the server, the SDK, and every view.
  public var voted: Bool = false

  public var isFollowing: Bool = false

  /// Whether the caller wrote it, so a client can offer to withdraw it.
  public var isAuthor: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DRFeatureRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var appID: String {
    get {return _storage._appID}
    set {_uniqueStorage()._appID = newValue}
  }

  /// Absent when the author has been deleted, or when the request was created in
  /// the console rather than by a user. A request with no author is normal.
  public var author: DRUserRef {
    get {return _storage._author ?? DRUserRef()}
    set {_uniqueStorage()._author = newValue}
  }
  /// Returns true if `author` has been explicitly set.
  public var hasAuthor: Bool {return _storage._author != nil}
  /// Clears the value of `author`. Subsequent reads from it will return its default value.
  public mutating func clearAuthor() {_uniqueStorage()._author = nil}

  public var title: String {
    get {return _storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  public var body: String {
    get {return _storage._body}
    set {_uniqueStorage()._body = newValue}
  }

  /// Demand. Counted, not summed from a returned list — the list is paginated and
  /// the count is not.
  public var voteCount: Int32 {
    get {return _storage._voteCount}
    set {_uniqueStorage()._voteCount = newValue}
  }

  public var commentCount: Int32 {
    get {return _storage._commentCount}
    set {_uniqueStorage()._commentCount = newValue}
  }

  /// Absent for an app-key caller, who is nobody in particular.
  public var viewer: DRViewerState {
    get {return _storage._viewer ?? DRViewerState()}
    set {_uniqueStorage()._viewer = newValue}
  }
  /// Returns true if `viewer` has been explicitly set.
  public var hasViewer: Bool {return _storage._viewer != nil}
  /// Clears the value of `viewer`. Subsequent reads from it will return its default value.
  public mutating func clearViewer() {_uniqueStorage()._viewer = nil}

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return _storage._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {_uniqueStorage()._createdAt = nil}

  public var updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._updatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._updatedAt = newValue}
  }
  /// Returns true if `updatedAt` has been explicitly set.
  public var hasUpdatedAt: Bool {return _storage._updatedAt != nil}
  /// Clears the value of `updatedAt`. Subsequent reads from it will return its default value.
  public mutating func clearUpdatedAt() {_uniqueStorage()._updatedAt = nil}

  /// Where this request sits, carrying what that answer means.
  ///
  /// Unset is a request written before this field existed, or by a client newer
  /// than this one. A reader draws what it can and says nothing about the rest;
  /// it is not an error.
  public var state: OneOf_State? {
    get {return _storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  public var `open`: DRRequestOpen {
    get {
      if case .open(let v)? = _storage._state {return v}
      return DRRequestOpen()
    }
    set {_uniqueStorage()._state = .open(newValue)}
  }

  public var planned: DRRequestPlanned {
    get {
      if case .planned(let v)? = _storage._state {return v}
      return DRRequestPlanned()
    }
    set {_uniqueStorage()._state = .planned(newValue)}
  }

  public var inProgress: DRRequestInProgress {
    get {
      if case .inProgress(let v)? = _storage._state {return v}
      return DRRequestInProgress()
    }
    set {_uniqueStorage()._state = .inProgress(newValue)}
  }

  public var shipped: DRRequestShipped {
    get {
      if case .shipped(let v)? = _storage._state {return v}
      return DRRequestShipped()
    }
    set {_uniqueStorage()._state = .shipped(newValue)}
  }

  public var declined: DRRequestDecline {
    get {
      if case .declined(let v)? = _storage._state {return v}
      return DRRequestDecline()
    }
    set {_uniqueStorage()._state = .declined(newValue)}
  }

  public var duplicate: DRRequestDuplicate {
    get {
      if case .duplicate(let v)? = _storage._state {return v}
      return DRRequestDuplicate()
    }
    set {_uniqueStorage()._state = .duplicate(newValue)}
  }

  /// When the request entered the state above. What "recently triaged" sorts on
  /// and what the changelog reads. Distinct from updated_at, which also moves
  /// when a vote lands.
  public var enteredStateAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._enteredStateAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._enteredStateAt = newValue}
  }
  /// Returns true if `enteredStateAt` has been explicitly set.
  public var hasEnteredStateAt: Bool {return _storage._enteredStateAt != nil}
  /// Clears the value of `enteredStateAt`. Subsequent reads from it will return its default value.
  public mutating func clearEnteredStateAt() {_uniqueStorage()._enteredStateAt = nil}

  /// How many other requests were folded into this one, so a list can say a row
  /// answers for more people than its own vote count suggests. Counted rather
  /// than summed from a returned list, the same as the two counts above; the
  /// duplicates themselves come back on the detail read.
  public var duplicateCount: Int32 {
    get {return _storage._duplicateCount}
    set {_uniqueStorage()._duplicateCount = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Where this request sits, carrying what that answer means.
  ///
  /// Unset is a request written before this field existed, or by a client newer
  /// than this one. A reader draws what it can and says nothing about the rest;
  /// it is not an error.
  public enum OneOf_State: Equatable, Sendable {
    case `open`(DRRequestOpen)
    case planned(DRRequestPlanned)
    case inProgress(DRRequestInProgress)
    case shipped(DRRequestShipped)
    case declined(DRRequestDecline)
    case duplicate(DRRequestDuplicate)

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// A comment an operator has taken down.
///
/// It carries no text, which is the point: a hidden comment used to be a body
/// field beside an `is_hidden` flag, and `{is_hidden: true, body: "…"}` was a
/// legal message. One line of Swift emptied it on one read path, so any second
/// reader — a console page, a push payload, a future GetComment — would have
/// served the text a moderator removed.
///
/// Whoever builds hiding keeps the original in storage, not here: the row is what
/// makes the decision reversible and stops the same abuse being re-reported, and
/// storage is where a fact the wire must never carry belongs.
public struct DRCommentHidden: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hiddenAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _hiddenAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_hiddenAt = newValue}
  }
  /// Returns true if `hiddenAt` has been explicitly set.
  public var hasHiddenAt: Bool {return self._hiddenAt != nil}
  /// Clears the value of `hiddenAt`. Subsequent reads from it will return its default value.
  public mutating func clearHiddenAt() {self._hiddenAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _hiddenAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct DRComment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var requestID: String = String()

  /// Absent for a deleted author, as on FeatureRequest.
  public var author: DRUserRef {
    get {return _author ?? DRUserRef()}
    set {_author = newValue}
  }
  /// Returns true if `author` has been explicitly set.
  public var hasAuthor: Bool {return self._author != nil}
  /// Clears the value of `author`. Subsequent reads from it will return its default value.
  public mutating func clearAuthor() {self._author = nil}

  public var authorRole: DRCommentAuthorRole = .unspecified

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  /// What this comment says, or that it no longer says it.
  ///
  /// Unset is a row written before this field existed, or by a server newer than
  /// this client. A reader draws nothing for it rather than an empty bubble.
  public var content: DRComment.OneOf_Content? = nil

  public var body: String {
    get {
      if case .body(let v)? = content {return v}
      return String()
    }
    set {content = .body(newValue)}
  }

  public var hidden: DRCommentHidden {
    get {
      if case .hidden(let v)? = content {return v}
      return DRCommentHidden()
    }
    set {content = .hidden(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// What this comment says, or that it no longer says it.
  ///
  /// Unset is a row written before this field existed, or by a server newer than
  /// this client. A reader draws nothing for it rather than an empty bubble.
  public enum OneOf_Content: Equatable, Sendable {
    case body(String)
    case hidden(DRCommentHidden)

  }

  public init() {}

  fileprivate var _author: DRUserRef? = nil
  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// A request you authored, voted for, or follow changed state.
public struct DRStatusChangedNews: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The status it moved to. A tag, not the request's whole state: an inbox row
  /// says "moved to Planned" and taps through for the rest.
  public var newStatus: DRRequestStatus = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Someone commented on a request you follow.
public struct DRCommentAddedNews: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A request you followed turned out to already be on the board.
public struct DRRequestDuplicateNews: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Where the vote went, so a tap lands on the request that now holds it.
  /// Required by this shape rather than by a comment.
  public var duplicateOfRequestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// One item in an end user's inbox.
///
/// Carries the request title rather than only its id, so an inbox renders in one
/// read and a push notification body can be built without a second lookup.
public struct DRNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var userID: String = String()

  public var requestID: String = String()

  public var requestTitle: String = String()

  /// Absent while unread. A timestamp rather than a bool so "mark all read"
  /// records when, and so an unread badge is a count of absences.
  public var readAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _readAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_readAt = newValue}
  }
  /// Returns true if `readAt` has been explicitly set.
  public var hasReadAt: Bool {return self._readAt != nil}
  /// Clears the value of `readAt`. Subsequent reads from it will return its default value.
  public mutating func clearReadAt() {self._readAt = nil}

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  /// What happened. Unset is a row written before this field existed, or by a
  /// server newer than this client: an inbox draws the title it already has and
  /// says nothing it cannot support.
  public var news: DRNotification.OneOf_News? = nil

  public var statusChanged: DRStatusChangedNews {
    get {
      if case .statusChanged(let v)? = news {return v}
      return DRStatusChangedNews()
    }
    set {news = .statusChanged(newValue)}
  }

  public var commentAdded: DRCommentAddedNews {
    get {
      if case .commentAdded(let v)? = news {return v}
      return DRCommentAddedNews()
    }
    set {news = .commentAdded(newValue)}
  }

  public var requestDuplicated: DRRequestDuplicateNews {
    get {
      if case .requestDuplicated(let v)? = news {return v}
      return DRRequestDuplicateNews()
    }
    set {news = .requestDuplicated(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// What happened. Unset is a row written before this field existed, or by a
  /// server newer than this client: an inbox draws the title it already has and
  /// says nothing it cannot support.
  public enum OneOf_News: Equatable, Sendable {
    case statusChanged(DRStatusChangedNews)
    case commentAdded(DRCommentAddedNews)
    case requestDuplicated(DRRequestDuplicateNews)

  }

  public init() {}

  fileprivate var _readAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct DRDeviceRegistration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  /// The APNs device token, hex. Rotates on reinstall and can be silently
  /// invalidated by Apple, so registration is an upsert the client repeats on
  /// every launch rather than a one-time write.
  public var token: String = String()

  public var environment: DRPushEnvironment = .unspecified

  public var registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _registeredAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_registeredAt = newValue}
  }
  /// Returns true if `registeredAt` has been explicitly set.
  public var hasRegisteredAt: Bool {return self._registeredAt != nil}
  /// Clears the value of `registeredAt`. Subsequent reads from it will return its default value.
  public mutating func clearRegisteredAt() {self._registeredAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// A published note about something that shipped.
///
/// Separate from a SHIPPED request rather than derived from one: a release is
/// usually several requests plus work nobody asked for, and it needs prose the
/// requests do not have.
public struct DRChangelogEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var appID: String = String()

  public var title: String = String()

  public var body: String = String()

  /// Optional version string as the host app spells it — "2.4.0". Free text
  /// because it has to match what the developer shipped, not a scheme of ours.
  public var version: String = String()

  /// Requests this release answers, so the people who asked can be told and the
  /// entry can link back to what they filed.
  public var requestIds: [String] = []

  /// Absent while a draft. Presence is what makes an entry public, so an
  /// unpublished entry is never a filter a caller can spell wrong.
  public var publishedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _publishedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_publishedAt = newValue}
  }
  /// Returns true if `publishedAt` has been explicitly set.
  public var hasPublishedAt: Bool {return self._publishedAt != nil}
  /// Clears the value of `publishedAt`. Subsequent reads from it will return its default value.
  public mutating func clearPublishedAt() {self._publishedAt = nil}

  /// When the entry came into existence, which for a draft is when the request
  /// it answers shipped. Always present, unlike published_at, so an entry can
  /// be ordered and addressed before anybody has published it.
  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {self._createdAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _publishedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// One column of the public roadmap.
///
/// Grouped by status rather than by a tenant-defined column set: the roadmap and
/// the triage queue must show the same truth, and a second grouping to keep in
/// sync with status would drift from it.
public struct DRRoadmapColumn: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: DRRequestStatus = .unspecified

  /// The column's requests, ranked by demand. Deliberately a bounded page — a
  /// roadmap is a summary, and a column with 400 planned items is answered by
  /// the board, not the roadmap.
  public var requests: [DRFeatureRequest] = []

  /// How many the column holds in total, which is usually more than were
  /// returned.
  public var totalCount: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "differentrequests.v1"

extension DRPlan: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLAN_UNSPECIFIED\0\u{1}PLAN_FREE\0\u{1}PLAN_PRO\0")
}

extension DRRequestStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REQUEST_STATUS_UNSPECIFIED\0\u{1}REQUEST_STATUS_OPEN\0\u{1}REQUEST_STATUS_PLANNED\0\u{1}REQUEST_STATUS_IN_PROGRESS\0\u{1}REQUEST_STATUS_SHIPPED\0\u{1}REQUEST_STATUS_DECLINED\0\u{1}REQUEST_STATUS_DUPLICATE\0")
}

extension DRCommentAuthorRole: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0COMMENT_AUTHOR_ROLE_UNSPECIFIED\0\u{1}COMMENT_AUTHOR_ROLE_USER\0\u{1}COMMENT_AUTHOR_ROLE_TEAM\0")
}

extension DRPushEnvironment: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PUSH_ENVIRONMENT_UNSPECIFIED\0\u{1}PUSH_ENVIRONMENT_SANDBOX\0\u{1}PUSH_ENVIRONMENT_PRODUCTION\0")
}

extension DRApp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".App"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}tenant_id\0\u{1}name\0\u{3}created_at\0\u{1}plan\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.tenantID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.plan) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.tenantID.isEmpty {
      try visitor.visitSingularStringField(value: self.tenantID, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.plan != .unspecified {
      try visitor.visitSingularEnumField(value: self.plan, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRApp, rhs: DRApp) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.tenantID != rhs.tenantID {return false}
    if lhs.name != rhs.name {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.plan != rhs.plan {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DREndUser: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EndUser"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}external_id\0\u{1}email\0\u{3}display_name\0\u{1}traits\0\u{3}created_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.externalID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.email) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.traits) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.externalID.isEmpty {
      try visitor.visitSingularStringField(value: self.externalID, fieldNumber: 2)
    }
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 3)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 4)
    }
    if !self.traits.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.traits, fieldNumber: 5)
    }
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DREndUser, rhs: DREndUser) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.externalID != rhs.externalID {return false}
    if lhs.email != rhs.email {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.traits != rhs.traits {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRUserRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}display_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRUserRef, rhs: DRUserRef) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRDeclineReason: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeclineReason"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}app_id\0\u{1}label\0\u{1}description\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRDeclineReason, rhs: DRDeclineReason) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.appID != rhs.appID {return false}
    if lhs.label != rhs.label {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestDecline: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestDecline"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0\u{1}note\0\u{b}declined_at\0\u{c}\u{3}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._reason) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.note) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reason {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.note.isEmpty {
      try visitor.visitSingularStringField(value: self.note, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestDecline, rhs: DRRequestDecline) -> Bool {
    if lhs._reason != rhs._reason {return false}
    if lhs.note != rhs.note {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestOpen: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestOpen"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestOpen, rhs: DRRequestOpen) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestPlanned: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestPlanned"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestPlanned, rhs: DRRequestPlanned) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestInProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestInProgress"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestInProgress, rhs: DRRequestInProgress) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestShipped: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestShipped"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestShipped, rhs: DRRequestShipped) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestDuplicate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestDuplicate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}duplicate_of_request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.duplicateOfRequestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.duplicateOfRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.duplicateOfRequestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestDuplicate, rhs: DRRequestDuplicate) -> Bool {
    if lhs.duplicateOfRequestID != rhs.duplicateOfRequestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRViewerState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ViewerState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}voted\0\u{3}is_following\0\u{3}is_author\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.voted) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isFollowing) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isAuthor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.voted != false {
      try visitor.visitSingularBoolField(value: self.voted, fieldNumber: 1)
    }
    if self.isFollowing != false {
      try visitor.visitSingularBoolField(value: self.isFollowing, fieldNumber: 2)
    }
    if self.isAuthor != false {
      try visitor.visitSingularBoolField(value: self.isAuthor, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRViewerState, rhs: DRViewerState) -> Bool {
    if lhs.voted != rhs.voted {return false}
    if lhs.isFollowing != rhs.isFollowing {return false}
    if lhs.isAuthor != rhs.isAuthor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRFeatureRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FeatureRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}app_id\0\u{1}author\0\u{1}title\0\u{1}body\0\u{4}\u{4}vote_count\0\u{3}comment_count\0\u{1}viewer\0\u{3}created_at\0\u{3}updated_at\0\u{2}\u{2}open\0\u{1}planned\0\u{3}in_progress\0\u{1}shipped\0\u{1}declined\0\u{1}duplicate\0\u{3}entered_state_at\0\u{3}duplicate_count\0\u{b}status\0\u{b}decline\0\u{b}merged_into_request_id\0\u{b}status_changed_at\0\u{c}\u{6}\u{1}\u{c}\u{7}\u{1}\u{c}\u{8}\u{1}\u{c}\u{e}\u{1}")

  fileprivate class _StorageClass {
    var _id: String = String()
    var _appID: String = String()
    var _author: DRUserRef? = nil
    var _title: String = String()
    var _body: String = String()
    var _voteCount: Int32 = 0
    var _commentCount: Int32 = 0
    var _viewer: DRViewerState? = nil
    var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _state: DRFeatureRequest.OneOf_State?
    var _enteredStateAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _duplicateCount: Int32 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _appID = source._appID
      _author = source._author
      _title = source._title
      _body = source._body
      _voteCount = source._voteCount
      _commentCount = source._commentCount
      _viewer = source._viewer
      _createdAt = source._createdAt
      _updatedAt = source._updatedAt
      _state = source._state
      _enteredStateAt = source._enteredStateAt
      _duplicateCount = source._duplicateCount
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._appID) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._author) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._body) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._voteCount) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._commentCount) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._viewer) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._createdAt) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._updatedAt) }()
        case 15: try {
          var v: DRRequestOpen?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .open(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .open(v)
          }
        }()
        case 16: try {
          var v: DRRequestPlanned?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .planned(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .planned(v)
          }
        }()
        case 17: try {
          var v: DRRequestInProgress?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .inProgress(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .inProgress(v)
          }
        }()
        case 18: try {
          var v: DRRequestShipped?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .shipped(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .shipped(v)
          }
        }()
        case 19: try {
          var v: DRRequestDecline?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .declined(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .declined(v)
          }
        }()
        case 20: try {
          var v: DRRequestDuplicate?
          var hadOneofValue = false
          if let current = _storage._state {
            hadOneofValue = true
            if case .duplicate(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._state = .duplicate(v)
          }
        }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._enteredStateAt) }()
        case 22: try { try decoder.decodeSingularInt32Field(value: &_storage._duplicateCount) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._appID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._appID, fieldNumber: 2)
      }
      try { if let v = _storage._author {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 4)
      }
      if !_storage._body.isEmpty {
        try visitor.visitSingularStringField(value: _storage._body, fieldNumber: 5)
      }
      if _storage._voteCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._voteCount, fieldNumber: 9)
      }
      if _storage._commentCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._commentCount, fieldNumber: 10)
      }
      try { if let v = _storage._viewer {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._createdAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._updatedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      switch _storage._state {
      case .open?: try {
        guard case .open(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      }()
      case .planned?: try {
        guard case .planned(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      }()
      case .inProgress?: try {
        guard case .inProgress(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      }()
      case .shipped?: try {
        guard case .shipped(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      }()
      case .declined?: try {
        guard case .declined(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 19)
      }()
      case .duplicate?: try {
        guard case .duplicate(let v)? = _storage._state else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      }()
      case nil: break
      }
      try { if let v = _storage._enteredStateAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
      if _storage._duplicateCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._duplicateCount, fieldNumber: 22)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRFeatureRequest, rhs: DRFeatureRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._appID != rhs_storage._appID {return false}
        if _storage._author != rhs_storage._author {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._body != rhs_storage._body {return false}
        if _storage._voteCount != rhs_storage._voteCount {return false}
        if _storage._commentCount != rhs_storage._commentCount {return false}
        if _storage._viewer != rhs_storage._viewer {return false}
        if _storage._createdAt != rhs_storage._createdAt {return false}
        if _storage._updatedAt != rhs_storage._updatedAt {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._enteredStateAt != rhs_storage._enteredStateAt {return false}
        if _storage._duplicateCount != rhs_storage._duplicateCount {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRCommentHidden: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommentHidden"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}hidden_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._hiddenAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._hiddenAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRCommentHidden, rhs: DRCommentHidden) -> Bool {
    if lhs._hiddenAt != rhs._hiddenAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRComment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Comment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}request_id\0\u{1}author\0\u{3}author_role\0\u{4}\u{3}created_at\0\u{1}body\0\u{1}hidden\0\u{b}is_hidden\0\u{c}\u{5}\u{1}\u{c}\u{6}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._author) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.authorRole) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      case 8: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.content != nil {try decoder.handleConflictingOneOf()}
          self.content = .body(v)
        }
      }()
      case 9: try {
        var v: DRCommentHidden?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .hidden(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .hidden(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 2)
    }
    try { if let v = self._author {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.authorRole != .unspecified {
      try visitor.visitSingularEnumField(value: self.authorRole, fieldNumber: 4)
    }
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    switch self.content {
    case .body?: try {
      guard case .body(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    }()
    case .hidden?: try {
      guard case .hidden(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRComment, rhs: DRComment) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs._author != rhs._author {return false}
    if lhs.authorRole != rhs.authorRole {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRStatusChangedNews: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StatusChangedNews"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.newStatus) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.newStatus != .unspecified {
      try visitor.visitSingularEnumField(value: self.newStatus, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRStatusChangedNews, rhs: DRStatusChangedNews) -> Bool {
    if lhs.newStatus != rhs.newStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRCommentAddedNews: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommentAddedNews"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRCommentAddedNews, rhs: DRCommentAddedNews) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRequestDuplicateNews: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestDuplicateNews"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}duplicate_of_request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.duplicateOfRequestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.duplicateOfRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.duplicateOfRequestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRequestDuplicateNews, rhs: DRRequestDuplicateNews) -> Bool {
    if lhs.duplicateOfRequestID != rhs.duplicateOfRequestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Notification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}user_id\0\u{4}\u{2}request_id\0\u{3}request_title\0\u{4}\u{3}read_at\0\u{3}created_at\0\u{3}status_changed\0\u{3}comment_added\0\u{3}request_duplicated\0\u{b}kind\0\u{b}new_status\0\u{b}merged_into_request_id\0\u{c}\u{3}\u{1}\u{c}\u{6}\u{1}\u{c}\u{7}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.requestTitle) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._readAt) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      case 10: try {
        var v: DRStatusChangedNews?
        var hadOneofValue = false
        if let current = self.news {
          hadOneofValue = true
          if case .statusChanged(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.news = .statusChanged(v)
        }
      }()
      case 11: try {
        var v: DRCommentAddedNews?
        var hadOneofValue = false
        if let current = self.news {
          hadOneofValue = true
          if case .commentAdded(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.news = .commentAdded(v)
        }
      }()
      case 12: try {
        var v: DRRequestDuplicateNews?
        var hadOneofValue = false
        if let current = self.news {
          hadOneofValue = true
          if case .requestDuplicated(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.news = .requestDuplicated(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 2)
    }
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 4)
    }
    if !self.requestTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.requestTitle, fieldNumber: 5)
    }
    try { if let v = self._readAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    switch self.news {
    case .statusChanged?: try {
      guard case .statusChanged(let v)? = self.news else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .commentAdded?: try {
      guard case .commentAdded(let v)? = self.news else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .requestDuplicated?: try {
      guard case .requestDuplicated(let v)? = self.news else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRNotification, rhs: DRNotification) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.requestTitle != rhs.requestTitle {return false}
    if lhs._readAt != rhs._readAt {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.news != rhs.news {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRDeviceRegistration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceRegistration"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}token\0\u{1}environment\0\u{3}registered_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.token) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.environment) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._registeredAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 2)
    }
    if self.environment != .unspecified {
      try visitor.visitSingularEnumField(value: self.environment, fieldNumber: 3)
    }
    try { if let v = self._registeredAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRDeviceRegistration, rhs: DRDeviceRegistration) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.token != rhs.token {return false}
    if lhs.environment != rhs.environment {return false}
    if lhs._registeredAt != rhs._registeredAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRChangelogEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChangelogEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}app_id\0\u{1}title\0\u{1}body\0\u{1}version\0\u{3}request_ids\0\u{3}published_at\0\u{3}created_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.requestIds) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._publishedAt) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 2)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 3)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 4)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 5)
    }
    if !self.requestIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.requestIds, fieldNumber: 6)
    }
    try { if let v = self._publishedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRChangelogEntry, rhs: DRChangelogEntry) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.appID != rhs.appID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.body != rhs.body {return false}
    if lhs.version != rhs.version {return false}
    if lhs.requestIds != rhs.requestIds {return false}
    if lhs._publishedAt != rhs._publishedAt {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DRRoadmapColumn: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RoadmapColumn"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}requests\0\u{3}total_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.requests) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.totalCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if !self.requests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.requests, fieldNumber: 2)
    }
    if self.totalCount != 0 {
      try visitor.visitSingularInt32Field(value: self.totalCount, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRoadmapColumn, rhs: DRRoadmapColumn) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.requests != rhs.requests {return false}
    if lhs.totalCount != rhs.totalCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
