// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: differentrequests_options.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The *minimum* credential a caller must present. Every rpc names exactly one;
/// there is no "any" and no default, so an rpc that forgets to say is a generator
/// error rather than an open endpoint.
///
/// Minimum, not exact: an end-user session is always accompanied by an app key, so
/// an rpc marked APP_KEY also serves a session caller — and populates the
/// viewer-relative fields it would otherwise omit. The reverse never holds. An rpc
/// marked END_USER rejects a bare app key.
///
/// There are deliberately no console or platform-admin values. Those surfaces are
/// server-rendered HTML in a private repository and have no rpcs to mark, so a
/// value for them would name a caller that does not exist.
public enum DRAudience: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never valid on an rpc. Present because proto3 requires a zero value, and an
  /// unset audience must fail loudly rather than resolve to the weakest one.
  case unspecified // = 0

  /// `X-App-Key: dr_<hex>` alone. Identifies the tenant's app but nobody within
  /// it, so these rpcs may not read or write anything user-scoped.
  case appKey // = 1

  /// App key plus an end-user session token issued by CreateSession. Everything an
  /// SDK caller does on behalf of a person: submit, vote, follow, comment, read
  /// their inbox.
  case endUser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .appKey
    case 2: self = .endUser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .appKey: return 1
    case .endUser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRAudience] = [
    .unspecified,
    .appKey,
    .endUser,
  ]

}

public enum DRHttpMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case get // = 1
  case post // = 2
  case put // = 3
  case delete // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .get
    case 2: self = .post
    case 3: self = .put
    case 4: self = .delete
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .get: return 1
    case .post: return 2
    case .put: return 3
    case .delete: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRHttpMethod] = [
    .unspecified,
    .get,
    .post,
    .put,
    .delete,
  ]

}

public struct DRRoute: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var method: DRHttpMethod = .unspecified

  /// Path template relative to the API root, with `{brace}` parameters —
  /// `/requests/{requestId}/comments`. A parameter name matches the field in the
  /// rpc's request message that supplies it, which is what lets the generator bind
  /// it without a second mapping to keep in sync.
  public var path: String = String()

  public var audience: DRAudience = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Extension support defined in differentrequests_options.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  public var DRurlToken: String {
    get {return getExtensionValue(ext: DRExtensions_url_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_url_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_url_token`
  /// has been explicitly set.
  public var hasDRurlToken: Bool {
    return hasExtensionValue(ext: DRExtensions_url_token)
  }
  /// Clears the value of extension `DRExtensions_url_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRurlToken() {
    clearExtensionValue(ext: DRExtensions_url_token)
  }

  public var DRtoken: String {
    get {return getExtensionValue(ext: DRExtensions_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_token`
  /// has been explicitly set.
  public var hasDRtoken: Bool {
    return hasExtensionValue(ext: DRExtensions_token)
  }
  /// Clears the value of extension `DRExtensions_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRtoken() {
    clearExtensionValue(ext: DRExtensions_token)
  }
}

extension SwiftProtobuf.Google_Protobuf_MethodOptions {

  public var DRroute: DRRoute {
    get {return getExtensionValue(ext: DRExtensions_route) ?? DRRoute()}
    set {setExtensionValue(ext: DRExtensions_route, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route`
  /// has been explicitly set.
  public var hasDRroute: Bool {
    return hasExtensionValue(ext: DRExtensions_route)
  }
  /// Clears the value of extension `DRExtensions_route`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRroute() {
    clearExtensionValue(ext: DRExtensions_route)
  }

}

// MARK: - File's ExtensionMap: DRDifferentrequestsOptions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let DRDifferentrequestsOptions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  DRExtensions_route,
  DRExtensions_url_token,
  DRExtensions_token
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let DRExtensions_route = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<DRRoute>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51240,
  fieldName: "differentrequests.v1.route"
)

public let DRExtensions_url_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51241,
  fieldName: "differentrequests.v1.url_token"
)

public let DRExtensions_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51242,
  fieldName: "differentrequests.v1.token"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "differentrequests.v1"

extension DRAudience: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIENCE_UNSPECIFIED\0\u{1}AUDIENCE_APP_KEY\0\u{1}AUDIENCE_END_USER\0")
}

extension DRHttpMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HTTP_METHOD_UNSPECIFIED\0\u{1}HTTP_METHOD_GET\0\u{1}HTTP_METHOD_POST\0\u{1}HTTP_METHOD_PUT\0\u{1}HTTP_METHOD_DELETE\0")
}

extension DRRoute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Route"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}method\0\u{1}path\0\u{1}audience\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.method) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.audience) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.method != .unspecified {
      try visitor.visitSingularEnumField(value: self.method, fieldNumber: 1)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 2)
    }
    if self.audience != .unspecified {
      try visitor.visitSingularEnumField(value: self.audience, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DRRoute, rhs: DRRoute) -> Bool {
    if lhs.method != rhs.method {return false}
    if lhs.path != rhs.path {return false}
    if lhs.audience != rhs.audience {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
