// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: differentrequests_options.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The *minimum* credential a caller must present. Every rpc names exactly one;
/// there is no "any" and no default, so an rpc that forgets to say is a generator
/// error rather than an open endpoint.
///
/// Minimum, not exact: an end-user session is always accompanied by an app key, so
/// an rpc marked APP_KEY also serves a session caller — and populates the
/// viewer-relative fields it would otherwise omit. The reverse never holds. An rpc
/// marked END_USER rejects a bare app key.
///
/// There are deliberately no console or platform-admin values. Those surfaces are
/// server-rendered HTML in a private repository and have no rpcs to mark, so a
/// value for them would name a caller that does not exist.
public enum DRAudience: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never valid on an rpc. Present because proto3 requires a zero value, and an
  /// unset audience must fail loudly rather than resolve to the weakest one.
  case unspecified // = 0

  /// `X-App-Key: dr_<hex>` alone. Identifies the tenant's app but nobody within
  /// it, so these rpcs may not read or write anything user-scoped.
  case appKey // = 1

  /// App key plus an end-user session token issued by CreateSession. Everything an
  /// SDK caller does on behalf of a person: submit, vote, follow, comment, read
  /// their inbox.
  case endUser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .appKey
    case 2: self = .endUser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .appKey: return 1
    case .endUser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRAudience] = [
    .unspecified,
    .appKey,
    .endUser,
  ]

}

/// The verb an rpc is served at.
///
/// Each value spells itself, because a client has to put the verb on the wire and
/// the spelling is what goes there. Spelled in Swift instead, it was a switch that
/// mapped four values to four strings and answered GET for the two it could not
/// map — so an rpc whose route was incomplete would have been sent as a read.
///
/// HTTP_METHOD_UNSPECIFIED carries no spelling. There is nothing to send for it,
/// and a value with no spelling cannot be sent rather than being sent as something
/// else.
public enum DRHttpMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case get // = 1
  case post // = 2
  case put // = 3
  case delete // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .get
    case 2: self = .post
    case 3: self = .put
    case 4: self = .delete
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .get: return 1
    case .post: return 2
    case .put: return 3
    case .delete: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [DRHttpMethod] = [
    .unspecified,
    .get,
    .post,
    .put,
    .delete,
  ]

}

// MARK: - Extension support defined in differentrequests_options.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  public var DRurlToken: String {
    get {return getExtensionValue(ext: DRExtensions_url_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_url_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_url_token`
  /// has been explicitly set.
  public var hasDRurlToken: Bool {
    return hasExtensionValue(ext: DRExtensions_url_token)
  }
  /// Clears the value of extension `DRExtensions_url_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRurlToken() {
    clearExtensionValue(ext: DRExtensions_url_token)
  }

  public var DRtoken: String {
    get {return getExtensionValue(ext: DRExtensions_token) ?? String()}
    set {setExtensionValue(ext: DRExtensions_token, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_token`
  /// has been explicitly set.
  public var hasDRtoken: Bool {
    return hasExtensionValue(ext: DRExtensions_token)
  }
  /// Clears the value of extension `DRExtensions_token`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRtoken() {
    clearExtensionValue(ext: DRExtensions_token)
  }
}

extension SwiftProtobuf.Google_Protobuf_MethodOptions {

  public var DRrouteMethod: DRHttpMethod {
    get {return getExtensionValue(ext: DRExtensions_route_method) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_route_method, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_method`
  /// has been explicitly set.
  public var hasDRrouteMethod: Bool {
    return hasExtensionValue(ext: DRExtensions_route_method)
  }
  /// Clears the value of extension `DRExtensions_route_method`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRrouteMethod() {
    clearExtensionValue(ext: DRExtensions_route_method)
  }

  /// Path template relative to the API root, with `{brace}` parameters —
  /// `/requests/{requestId}/comments`. A parameter name matches the field in the
  /// rpc's request message that supplies it, which is what lets the generator bind
  /// it without a second mapping to keep in sync.
  public var DRroutePath: String {
    get {return getExtensionValue(ext: DRExtensions_route_path) ?? String()}
    set {setExtensionValue(ext: DRExtensions_route_path, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_path`
  /// has been explicitly set.
  public var hasDRroutePath: Bool {
    return hasExtensionValue(ext: DRExtensions_route_path)
  }
  /// Clears the value of extension `DRExtensions_route_path`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRroutePath() {
    clearExtensionValue(ext: DRExtensions_route_path)
  }

  public var DRrouteAudience: DRAudience {
    get {return getExtensionValue(ext: DRExtensions_route_audience) ?? .unspecified}
    set {setExtensionValue(ext: DRExtensions_route_audience, value: newValue)}
  }
  /// Returns true if extension `DRExtensions_route_audience`
  /// has been explicitly set.
  public var hasDRrouteAudience: Bool {
    return hasExtensionValue(ext: DRExtensions_route_audience)
  }
  /// Clears the value of extension `DRExtensions_route_audience`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearDRrouteAudience() {
    clearExtensionValue(ext: DRExtensions_route_audience)
  }

}

// MARK: - File's ExtensionMap: DRDifferentrequestsOptions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let DRDifferentrequestsOptions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  DRExtensions_route_method,
  DRExtensions_route_path,
  DRExtensions_route_audience,
  DRExtensions_url_token,
  DRExtensions_token
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public let DRExtensions_route_method = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRHttpMethod>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51243,
  fieldName: "differentrequests.v1.route_method"
)

/// Path template relative to the API root, with `{brace}` parameters —
/// `/requests/{requestId}/comments`. A parameter name matches the field in the
/// rpc's request message that supplies it, which is what lets the generator bind
/// it without a second mapping to keep in sync.
public let DRExtensions_route_path = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51244,
  fieldName: "differentrequests.v1.route_path"
)

public let DRExtensions_route_audience = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalEnumExtensionField<DRAudience>, SwiftProtobuf.Google_Protobuf_MethodOptions>(
  _protobuf_fieldNumber: 51245,
  fieldName: "differentrequests.v1.route_audience"
)

public let DRExtensions_url_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51241,
  fieldName: "differentrequests.v1.url_token"
)

public let DRExtensions_token = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 51242,
  fieldName: "differentrequests.v1.token"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DRAudience: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AUDIENCE_UNSPECIFIED\0\u{1}AUDIENCE_APP_KEY\0\u{1}AUDIENCE_END_USER\0")
}

extension DRHttpMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HTTP_METHOD_UNSPECIFIED\0\u{1}HTTP_METHOD_GET\0\u{1}HTTP_METHOD_POST\0\u{1}HTTP_METHOD_PUT\0\u{1}HTTP_METHOD_DELETE\0")
}
