// DO NOT EDIT.
//
// Generated by fields-gen from differentrequests_domain.proto. Run Scripts/generate.sh.

extension DRTenant {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let name = "name"
    public static let plan = "plan"
    public static let createdAt = "created_at"
  }
}

extension DRApp {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let tenantId = "tenant_id"
    public static let name = "name"
    public static let createdAt = "created_at"
  }
}

extension DREndUser {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let externalId = "external_id"
    public static let email = "email"
    public static let displayName = "display_name"
    public static let traits = "traits"
    public static let createdAt = "created_at"
  }
}

extension DRUserRef {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let displayName = "display_name"
  }
}

extension DRDeclineReason {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let appId = "app_id"
    public static let label = "label"
    public static let description = "description"
  }
}

extension DRRequestDecline {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let reason = "reason"
    public static let note = "note"
  }
}

extension DRRequestDuplicate {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let duplicateOfRequestId = "duplicate_of_request_id"
  }
}

extension DRViewerState {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let voted = "voted"
    public static let isFollowing = "is_following"
    public static let isAuthor = "is_author"
  }
}

extension DRFeatureRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let appId = "app_id"
    public static let author = "author"
    public static let title = "title"
    public static let body = "body"
    public static let voteCount = "vote_count"
    public static let commentCount = "comment_count"
    public static let viewer = "viewer"
    public static let createdAt = "created_at"
    public static let updatedAt = "updated_at"
    public static let open = "open"
    public static let planned = "planned"
    public static let inProgress = "in_progress"
    public static let shipped = "shipped"
    public static let declined = "declined"
    public static let duplicate = "duplicate"
    public static let enteredStateAt = "entered_state_at"
    public static let duplicateCount = "duplicate_count"
  }
}

extension DRFeatureRequest.OneOf_State {
  /// Which arm this is, spelled as the schema spells the field it stands for.
  ///
  /// For a log line or a diagnostic. Never for a caller to branch on — the arm itself is
  /// what a caller branches on, and the compiler is what makes that exhaustive.
  public var fieldName: String {
    switch self {
    case .`open`: return DRFeatureRequest.Field.open
    case .planned: return DRFeatureRequest.Field.planned
    case .inProgress: return DRFeatureRequest.Field.inProgress
    case .shipped: return DRFeatureRequest.Field.shipped
    case .declined: return DRFeatureRequest.Field.declined
    case .duplicate: return DRFeatureRequest.Field.duplicate
    }
  }
}

extension DRCommentHidden {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let hiddenAt = "hidden_at"
  }
}

extension DRComment {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let requestId = "request_id"
    public static let author = "author"
    public static let authorRole = "author_role"
    public static let createdAt = "created_at"
    public static let body = "body"
    public static let hidden = "hidden"
  }
}

extension DRComment.OneOf_Content {
  /// Which arm this is, spelled as the schema spells the field it stands for.
  ///
  /// For a log line or a diagnostic. Never for a caller to branch on — the arm itself is
  /// what a caller branches on, and the compiler is what makes that exhaustive.
  public var fieldName: String {
    switch self {
    case .body: return DRComment.Field.body
    case .hidden: return DRComment.Field.hidden
    }
  }
}

extension DRStatusChangedNews {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let newStatus = "new_status"
  }
}

extension DRRequestDuplicateNews {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let duplicateOfRequestId = "duplicate_of_request_id"
  }
}

extension DRNotification {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let userId = "user_id"
    public static let requestId = "request_id"
    public static let requestTitle = "request_title"
    public static let readAt = "read_at"
    public static let createdAt = "created_at"
    public static let statusChanged = "status_changed"
    public static let commentAdded = "comment_added"
    public static let requestDuplicated = "request_duplicated"
  }
}

extension DRNotification.OneOf_News {
  /// Which arm this is, spelled as the schema spells the field it stands for.
  ///
  /// For a log line or a diagnostic. Never for a caller to branch on — the arm itself is
  /// what a caller branches on, and the compiler is what makes that exhaustive.
  public var fieldName: String {
    switch self {
    case .statusChanged: return DRNotification.Field.statusChanged
    case .commentAdded: return DRNotification.Field.commentAdded
    case .requestDuplicated: return DRNotification.Field.requestDuplicated
    }
  }
}

extension DRDeviceRegistration {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let token = "token"
    public static let environment = "environment"
    public static let registeredAt = "registered_at"
  }
}

extension DRChangelogEntry {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let id = "id"
    public static let appId = "app_id"
    public static let title = "title"
    public static let body = "body"
    public static let version = "version"
    public static let requestIds = "request_ids"
    public static let publishedAt = "published_at"
  }
}

extension DRRoadmapColumn {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let status = "status"
    public static let requests = "requests"
    public static let totalCount = "total_count"
  }
}
