// DO NOT EDIT.
//
// Generated by fields-gen from differentrequests_sdk.proto. Run Scripts/generate.sh.

extension DRInvalidArgument {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let field = "field"
  }
}

extension DRRateLimited {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let retryAfterSeconds = "retry_after_seconds"
  }
}

extension DRApiError {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let message = "message"
    public static let invalidArgument = "invalid_argument"
    public static let malformed = "malformed"
    public static let unauthenticated = "unauthenticated"
    public static let permissionDenied = "permission_denied"
    public static let notFound = "not_found"
    public static let failedPrecondition = "failed_precondition"
    public static let conflict = "conflict"
    public static let planRequired = "plan_required"
    public static let rateLimited = "rate_limited"
    public static let internalFailure = "internal_failure"
  }
}

extension DRApiError.OneOf_Reason {
  /// Which arm this is, spelled as the schema spells the field it stands for.
  ///
  /// For a log line or a diagnostic. Never for a caller to branch on — the arm itself is
  /// what a caller branches on, and the compiler is what makes that exhaustive.
  public var fieldName: String {
    switch self {
    case .invalidArgument: return DRApiError.Field.invalidArgument
    case .malformed: return DRApiError.Field.malformed
    case .unauthenticated: return DRApiError.Field.unauthenticated
    case .permissionDenied: return DRApiError.Field.permissionDenied
    case .notFound: return DRApiError.Field.notFound
    case .failedPrecondition: return DRApiError.Field.failedPrecondition
    case .conflict: return DRApiError.Field.conflict
    case .planRequired: return DRApiError.Field.planRequired
    case .rateLimited: return DRApiError.Field.rateLimited
    case .internalFailure: return DRApiError.Field.internalFailure
    }
  }
}

extension DRAppConfig {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let app = "app"
    public static let roadmapEnabled = "roadmap_enabled"
    public static let changelogEnabled = "changelog_enabled"
    public static let commentsEnabled = "comments_enabled"
    public static let pushEnabled = "push_enabled"
    public static let developerRepliesEnabled = "developer_replies_enabled"
    public static let foldingEnabled = "folding_enabled"
    public static let appearanceEnabled = "appearance_enabled"
    public static let planningEnabled = "planning_enabled"
    public static let traitRankingEnabled = "trait_ranking_enabled"
    public static let badgeRemoved = "badge_removed"
  }
}

extension DRAppConfig {
  /// Whether this config includes a surface.
  ///
  /// Generated from the fields that name one, so the flag a surface is answered against is
  /// the flag the schema says answers for it — on every side that asks.
  ///
  /// An unspecified or unrecognized surface is not included. A tenant whose entitlement
  /// cannot be identified is served the tier that costs them nothing rather than handed a
  /// surface, which is the same reading an unknown plan gets.
  public func includes(_ surface: DRPlanSurface) -> Bool {
    switch surface {
    case .roadmap: return roadmapEnabled
    case .changelog: return changelogEnabled
    case .comments: return commentsEnabled
    case .push: return pushEnabled
    case .developerReplies: return developerRepliesEnabled
    case .folding: return foldingEnabled
    case .appearance: return appearanceEnabled
    case .planning: return planningEnabled
    case .traitRanking: return traitRankingEnabled
    case .badgeRemoval: return badgeRemoved
    case .unspecified, .UNRECOGNIZED: return false
    }
  }
}

extension DRGetConfigResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let config = "config"
  }
}

extension DRCreateSessionRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let externalId = "external_id"
    public static let email = "email"
    public static let displayName = "display_name"
    public static let traits = "traits"
    public static let proof = "proof"
  }
}

extension DRCreateSessionRequest {
  /// The longest each of this message's text fields may be, in characters, counted the way a
  /// person counts.
  ///
  /// The server refuses anything longer and the SDK counts against the same number, so a
  /// composer stops somebody where the refusal would have.
  public enum TextLimit {
    public static let externalID = 200
    public static let email = 320
    public static let displayName = 200
  }
}

extension DRIdentityProof {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let signature = "signature"
    public static let expiresAt = "expires_at"
  }
}

extension DRIdentityProof {
  /// The longest each of this message's text fields may be, in characters, counted the way a
  /// person counts.
  ///
  /// The server refuses anything longer and the SDK counts against the same number, so a
  /// composer stops somebody where the refusal would have.
  public enum TextLimit {
    public static let signature = 200
  }
}

extension DRCreateSessionResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let user = "user"
    public static let sessionToken = "session_token"
    public static let expiresAt = "expires_at"
  }
}

extension DRListRequestsRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let statuses = "statuses"
    public static let sort = "sort"
    public static let query = "query"
    public static let cursor = "cursor"
  }
}

extension DRListRequestsResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requests = "requests"
    public static let nextCursor = "next_cursor"
  }
}

extension DRGetRequestRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
  }
}

extension DRGetRequestResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
    public static let duplicates = "duplicates"
  }
}

extension DRCreateRequestRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let title = "title"
    public static let body = "body"
  }
}

extension DRCreateRequestRequest {
  /// The longest each of this message's text fields may be, in characters, counted the way a
  /// person counts.
  ///
  /// The server refuses anything longer and the SDK counts against the same number, so a
  /// composer stops somebody where the refusal would have.
  public enum TextLimit {
    public static let title = 200
    public static let body = 5000
  }
}

extension DRCreateRequestResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
  }
}

extension DRVoteRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
  }
}

extension DRVoteResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
  }
}

extension DRClearVoteRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
  }
}

extension DRClearVoteResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
  }
}

extension DRFollowRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
  }
}

extension DRFollowResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
  }
}

extension DRUnfollowRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
  }
}

extension DRUnfollowResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let request = "request"
  }
}

extension DRListCommentsRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
    public static let cursor = "cursor"
  }
}

extension DRListCommentsResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let comments = "comments"
    public static let nextCursor = "next_cursor"
  }
}

extension DRCreateCommentRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let requestId = "request_id"
    public static let body = "body"
  }
}

extension DRCreateCommentRequest {
  /// The longest each of this message's text fields may be, in characters, counted the way a
  /// person counts.
  ///
  /// The server refuses anything longer and the SDK counts against the same number, so a
  /// composer stops somebody where the refusal would have.
  public enum TextLimit {
    public static let body = 2000
  }
}

extension DRCreateCommentResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let comment = "comment"
  }
}

extension DRListNotificationsRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let cursor = "cursor"
  }
}

extension DRListNotificationsResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let notifications = "notifications"
    public static let nextCursor = "next_cursor"
  }
}

extension DRGetUnreadCountResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let unreadCount = "unread_count"
  }
}

extension DRMarkNotificationReadRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let notificationId = "notification_id"
  }
}

extension DRMarkNotificationReadResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let notification = "notification"
  }
}

extension DRMarkAllNotificationsReadResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let markedCount = "marked_count"
  }
}

extension DRRegisterDeviceRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let token = "token"
    public static let environment = "environment"
  }
}

extension DRRegisterDeviceRequest {
  /// The longest each of this message's text fields may be, in characters, counted the way a
  /// person counts.
  ///
  /// The server refuses anything longer and the SDK counts against the same number, so a
  /// composer stops somebody where the refusal would have.
  public enum TextLimit {
    public static let token = 200
  }
}

extension DRRegisterDeviceResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let device = "device"
  }
}

extension DRUnregisterDeviceRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let deviceId = "device_id"
  }
}

extension DRGetRoadmapResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let columns = "columns"
  }
}

extension DRListChangelogRequest {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let cursor = "cursor"
  }
}

extension DRListChangelogResponse {
  /// This message's field names, as the schema spells them. What a query key or a form field
  /// has to be called.
  public enum Field {
    public static let entries = "entries"
    public static let nextCursor = "next_cursor"
  }
}
