// DO NOT EDIT.
//
// Generated by price-gen from differentrequests_domain.proto. Run Scripts/generate.sh.

extension DRPriceStep {

  /// What this step adds to a monthly bill, in cents.
  ///
  /// Cents rather than a decimal, because money in a floating-point number is money that
  /// eventually does not add up.
  ///
  /// Absent for a value that declares no price, which is what keeps an unpriced step out of a
  /// total rather than silently adding nothing to one.
  public var monthlyCents: Int? {
    switch self {
    case .first: return 2900
    case .second: return 1500
    case .third: return 1000
    case .fourth: return 500
    case .eachAfter: return 500
    default: return nil
    }
  }
}
