// DO NOT EDIT.
//
// Generated by endpoint-gen from differentrequests_sdk.proto. Run Scripts/generate.sh.

/// Every rpc on `differentrequests.v1.RequestsService`, with the path it is called at and the
/// credential it requires.
///
/// The path is not a choice and is not written anywhere by hand: every rpc is a POST
/// to `/<package>.<Service>/<Method>` carrying its request message as a protobuf
/// binary body.
public enum RequestsServiceMethod: String, Sendable, CaseIterable {
  case getConfig = "/differentrequests.v1.RequestsService/GetConfig"
  case createSession = "/differentrequests.v1.RequestsService/CreateSession"
  case listRequests = "/differentrequests.v1.RequestsService/ListRequests"
  case getRequest = "/differentrequests.v1.RequestsService/GetRequest"
  case createRequest = "/differentrequests.v1.RequestsService/CreateRequest"
  case vote = "/differentrequests.v1.RequestsService/Vote"
  case clearVote = "/differentrequests.v1.RequestsService/ClearVote"
  case follow = "/differentrequests.v1.RequestsService/Follow"
  case unfollow = "/differentrequests.v1.RequestsService/Unfollow"
  case listComments = "/differentrequests.v1.RequestsService/ListComments"
  case createComment = "/differentrequests.v1.RequestsService/CreateComment"
  case listNotifications = "/differentrequests.v1.RequestsService/ListNotifications"
  case getUnreadCount = "/differentrequests.v1.RequestsService/GetUnreadCount"
  case markNotificationRead = "/differentrequests.v1.RequestsService/MarkNotificationRead"
  case markAllNotificationsRead = "/differentrequests.v1.RequestsService/MarkAllNotificationsRead"
  case registerDevice = "/differentrequests.v1.RequestsService/RegisterDevice"
  case unregisterDevice = "/differentrequests.v1.RequestsService/UnregisterDevice"
  case getRoadmap = "/differentrequests.v1.RequestsService/GetRoadmap"
  case listChangelog = "/differentrequests.v1.RequestsService/ListChangelog"

  /// The minimum credential a caller must present. A server rejects anything weaker;
  /// a client that has not authenticated knows before calling.
  public var audience: Audience {
    switch self {
    case .getConfig: return .appKey
    case .createSession: return .appKey
    case .listRequests: return .appKey
    case .getRequest: return .appKey
    case .createRequest: return .endUser
    case .vote: return .endUser
    case .clearVote: return .endUser
    case .follow: return .endUser
    case .unfollow: return .endUser
    case .listComments: return .appKey
    case .createComment: return .endUser
    case .listNotifications: return .endUser
    case .getUnreadCount: return .endUser
    case .markNotificationRead: return .endUser
    case .markAllNotificationsRead: return .endUser
    case .registerDevice: return .endUser
    case .unregisterDevice: return .endUser
    case .getRoadmap: return .appKey
    case .listChangelog: return .appKey
    }
  }

  /// The path this rpc is called at, relative to the API base URL.
  public var path: String { rawValue }
}
