// DO NOT EDIT.
//
// Generated by endpoint-gen from differentrequests_sdk.proto. Run Scripts/generate.sh.

/// Every rpc on `RequestsService`: the verb it answers, the path template it is registered
/// at, and the credential it requires.
///
/// A server builds its router from `allCases` and dispatches on the matched case, so an rpc
/// added to the contract breaks an exhaustive switch until it is handled.
public enum RequestsServiceRPC: String, Sendable, CaseIterable {
  case getConfig = "GetConfig"
  case createSession = "CreateSession"
  case listRequests = "ListRequests"
  case createRequest = "CreateRequest"
  case getRequest = "GetRequest"
  case vote = "Vote"
  case clearVote = "ClearVote"
  case follow = "Follow"
  case unfollow = "Unfollow"
  case listComments = "ListComments"
  case createComment = "CreateComment"
  case listNotifications = "ListNotifications"
  case getUnreadCount = "GetUnreadCount"
  case markAllNotificationsRead = "MarkAllNotificationsRead"
  case markNotificationRead = "MarkNotificationRead"
  case registerDevice = "RegisterDevice"
  case unregisterDevice = "UnregisterDevice"
  case getRoadmap = "GetRoadmap"
  case listChangelog = "ListChangelog"

  /// The verb this rpc answers.
  public var method: HttpMethod {
    switch self {
    case .getConfig: return .get
    case .createSession: return .post
    case .listRequests: return .get
    case .createRequest: return .post
    case .getRequest: return .get
    case .vote: return .put
    case .clearVote: return .delete
    case .follow: return .put
    case .unfollow: return .delete
    case .listComments: return .get
    case .createComment: return .post
    case .listNotifications: return .get
    case .getUnreadCount: return .get
    case .markAllNotificationsRead: return .put
    case .markNotificationRead: return .put
    case .registerDevice: return .put
    case .unregisterDevice: return .delete
    case .getRoadmap: return .get
    case .listChangelog: return .get
    }
  }

  /// The path template, `{brace}` parameters included, as a router wants it.
  public var template: String {
    switch self {
    case .getConfig: return "/config"
    case .createSession: return "/sessions"
    case .listRequests: return "/requests"
    case .createRequest: return "/requests"
    case .getRequest: return "/requests/{requestId}"
    case .vote: return "/requests/{requestId}/vote"
    case .clearVote: return "/requests/{requestId}/vote"
    case .follow: return "/requests/{requestId}/follow"
    case .unfollow: return "/requests/{requestId}/follow"
    case .listComments: return "/requests/{requestId}/comments"
    case .createComment: return "/requests/{requestId}/comments"
    case .listNotifications: return "/notifications"
    case .getUnreadCount: return "/notifications/unread-count"
    case .markAllNotificationsRead: return "/notifications/read-all"
    case .markNotificationRead: return "/notifications/{notificationId}/read"
    case .registerDevice: return "/devices"
    case .unregisterDevice: return "/devices/{deviceId}"
    case .getRoadmap: return "/roadmap"
    case .listChangelog: return "/changelog"
    }
  }

  /// The minimum credential a caller must present. A server rejects anything weaker.
  public var audience: Audience {
    switch self {
    case .getConfig: return .appKey
    case .createSession: return .appKey
    case .listRequests: return .appKey
    case .createRequest: return .endUser
    case .getRequest: return .appKey
    case .vote: return .endUser
    case .clearVote: return .endUser
    case .follow: return .endUser
    case .unfollow: return .endUser
    case .listComments: return .appKey
    case .createComment: return .endUser
    case .listNotifications: return .endUser
    case .getUnreadCount: return .endUser
    case .markAllNotificationsRead: return .endUser
    case .markNotificationRead: return .endUser
    case .registerDevice: return .endUser
    case .unregisterDevice: return .endUser
    case .getRoadmap: return .appKey
    case .listChangelog: return .appKey
    }
  }
}

/// One call to `RequestsService`, with the ids its path needs.
///
/// A client builds this and reads `path`. Nothing spells a path itself, and an rpc whose
/// path takes an id cannot be constructed without one.
///
/// Ids are interpolated raw. Percent-encoding belongs to whoever assembles the URL —
/// `URLComponents.path` does it correctly, and doing it here as well would double-encode.
public enum RequestsServiceEndpoint: Sendable {
  case getConfig
  case createSession
  case listRequests
  case createRequest
  case getRequest(requestId: String)
  case vote(requestId: String)
  case clearVote(requestId: String)
  case follow(requestId: String)
  case unfollow(requestId: String)
  case listComments(requestId: String)
  case createComment(requestId: String)
  case listNotifications
  case getUnreadCount
  case markAllNotificationsRead
  case markNotificationRead(notificationId: String)
  case registerDevice
  case unregisterDevice(deviceId: String)
  case getRoadmap
  case listChangelog

  /// The path to call, relative to the API base URL.
  public var path: String {
    switch self {
    case .getConfig: return "/config"
    case .createSession: return "/sessions"
    case .listRequests: return "/requests"
    case .createRequest: return "/requests"
    case .getRequest(let requestId): return "/requests/\(requestId)"
    case .vote(let requestId): return "/requests/\(requestId)/vote"
    case .clearVote(let requestId): return "/requests/\(requestId)/vote"
    case .follow(let requestId): return "/requests/\(requestId)/follow"
    case .unfollow(let requestId): return "/requests/\(requestId)/follow"
    case .listComments(let requestId): return "/requests/\(requestId)/comments"
    case .createComment(let requestId): return "/requests/\(requestId)/comments"
    case .listNotifications: return "/notifications"
    case .getUnreadCount: return "/notifications/unread-count"
    case .markAllNotificationsRead: return "/notifications/read-all"
    case .markNotificationRead(let notificationId): return "/notifications/\(notificationId)/read"
    case .registerDevice: return "/devices"
    case .unregisterDevice(let deviceId): return "/devices/\(deviceId)"
    case .getRoadmap: return "/roadmap"
    case .listChangelog: return "/changelog"
    }
  }

  /// Which rpc this is, for anything that needs the verb or the audience.
  public var rpc: RequestsServiceRPC {
    switch self {
    case .getConfig: return .getConfig
    case .createSession: return .createSession
    case .listRequests: return .listRequests
    case .createRequest: return .createRequest
    case .getRequest(let requestId): _ = requestId; return .getRequest
    case .vote(let requestId): _ = requestId; return .vote
    case .clearVote(let requestId): _ = requestId; return .clearVote
    case .follow(let requestId): _ = requestId; return .follow
    case .unfollow(let requestId): _ = requestId; return .unfollow
    case .listComments(let requestId): _ = requestId; return .listComments
    case .createComment(let requestId): _ = requestId; return .createComment
    case .listNotifications: return .listNotifications
    case .getUnreadCount: return .getUnreadCount
    case .markAllNotificationsRead: return .markAllNotificationsRead
    case .markNotificationRead(let notificationId): _ = notificationId; return .markNotificationRead
    case .registerDevice: return .registerDevice
    case .unregisterDevice(let deviceId): _ = deviceId; return .unregisterDevice
    case .getRoadmap: return .getRoadmap
    case .listChangelog: return .listChangelog
    }
  }
}
