// DO NOT EDIT.
//
// Generated by tokens-gen from differentrequests_sdk.proto. Run Scripts/generate.sh.

extension DRRequestSort {
  /// How this value is spelled in a URL.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unspellable value
  /// impossible to send rather than merely discouraged.
  public var urlToken: String? {
    switch self {
    case .top: return "top"
    case .new: return "new"
    default: return nil
    }
  }

  /// Reads a value back from its spelling in a URL.
  ///
  /// Nil for anything not in the contract, so an unrecognized spelling is rejected by the
  /// caller rather than silently becoming a default.
  public init?(urlToken: String) {
    switch urlToken {
    case "top": self = .top
    case "new": self = .new
    default: return nil
    }
  }
}
