// DO NOT EDIT.
//
// Generated by tokens-gen from differentrequests_domain.proto. Run Scripts/generate.sh.

extension DRPlan {
  /// How this value is spelled in a URL.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unspellable value
  /// impossible to send rather than merely discouraged.
  public var urlToken: String? {
    switch self {
    case .free: return "free"
    case .pro: return "pro"
    default: return nil
    }
  }

  /// Reads a value back from its spelling in a URL.
  ///
  /// Nil for anything not in the contract, so an unrecognized spelling is rejected by the
  /// caller rather than silently becoming a default.
  public init?(urlToken: String) {
    switch urlToken {
    case "free": self = .free
    case "pro": self = .pro
    default: return nil
    }
  }

  /// What a person is shown for this value.
  ///
  /// Total: every value of this enum declares one, so there is nothing to fall back to and
  /// no caller has to invent a word.
  public var label: String {
    switch self {
    case .unspecified: return "A plan this build does not know"
    case .free: return "Free"
    case .pro: return "Pro"
    case .UNRECOGNIZED: return "A plan this build does not know"
    }
  }
}

extension DRRequestStatus {
  /// How this value is spelled in a URL.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unspellable value
  /// impossible to send rather than merely discouraged.
  public var urlToken: String? {
    switch self {
    case .`open`: return "open"
    case .planned: return "planned"
    case .inProgress: return "in-progress"
    case .shipped: return "shipped"
    case .declined: return "declined"
    case .duplicate: return "duplicate"
    default: return nil
    }
  }

  /// Reads a value back from its spelling in a URL.
  ///
  /// Nil for anything not in the contract, so an unrecognized spelling is rejected by the
  /// caller rather than silently becoming a default.
  public init?(urlToken: String) {
    switch urlToken {
    case "open": self = .`open`
    case "planned": self = .planned
    case "in-progress": self = .inProgress
    case "shipped": self = .shipped
    case "declined": self = .declined
    case "duplicate": self = .duplicate
    default: return nil
    }
  }

  /// What a person is shown for this value.
  ///
  /// Total: every value of this enum declares one, so there is nothing to fall back to and
  /// no caller has to invent a word.
  public var label: String {
    switch self {
    case .unspecified: return "Unknown"
    case .`open`: return "Open"
    case .planned: return "Planned"
    case .inProgress: return "In Progress"
    case .shipped: return "Shipped"
    case .declined: return "Declined"
    case .duplicate: return "Duplicate"
    case .UNRECOGNIZED: return "Unknown"
    }
  }
}

extension DRNotificationHeadline {
  /// What a person is shown for this value.
  ///
  /// Total: every value of this enum declares one, so there is nothing to fall back to and
  /// no caller has to invent a word.
  public var label: String {
    switch self {
    case .unspecified: return "Updated"
    case .statusChanged: return "Now"
    case .commentAdded: return "New comment"
    case .requestDuplicated: return "Already on the board"
    case .UNRECOGNIZED: return "Updated"
    }
  }
}
