// DO NOT EDIT.
//
// Generated by tokens-gen from differentrequests_options.proto. Run Scripts/generate.sh.

extension DRHttpMethod {
  /// The exact string this value becomes when it leaves Swift.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unspellable value
  /// impossible to send rather than merely discouraged.
  public var token: String? {
    switch self {
    case .get: return "GET"
    case .post: return "POST"
    case .put: return "PUT"
    case .delete: return "DELETE"
    default: return nil
    }
  }

  /// Reads a value back from the string it becomes.
  ///
  /// Nil for anything not in the contract, so an unrecognized spelling is rejected by the
  /// caller rather than silently becoming a default.
  public init?(token: String) {
    switch token {
    case "GET": self = .get
    case "POST": self = .post
    case "PUT": self = .put
    case "DELETE": self = .delete
    default: return nil
    }
  }
}
