// DO NOT EDIT.
//
// Generated by tokens-gen from differentrequests_domain.proto. Run Scripts/generate.sh.

extension DRPlan {
  /// How this value is spelled in a URL.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unsendable value
  /// impossible to put in a query string rather than merely discouraged.
  public var urlToken: String? {
    switch self {
    case .free: return "free"
    case .pro: return "pro"
    default: return nil
    }
  }

  /// Reads a value back from its spelling. Nil for anything not in the contract, so an
  /// unrecognized token is rejected by the caller rather than silently becoming a default.
  public init?(urlToken: String) {
    switch urlToken {
    case "free": self = .free
    case "pro": self = .pro
    default: return nil
    }
  }
}

extension DRRequestStatus {
  /// How this value is spelled in a URL.
  ///
  /// Absent for a value with no declared spelling, which is what makes an unsendable value
  /// impossible to put in a query string rather than merely discouraged.
  public var urlToken: String? {
    switch self {
    case .`open`: return "open"
    case .planned: return "planned"
    case .inProgress: return "in-progress"
    case .shipped: return "shipped"
    case .declined: return "declined"
    case .merged: return "merged"
    default: return nil
    }
  }

  /// Reads a value back from its spelling. Nil for anything not in the contract, so an
  /// unrecognized token is rejected by the caller rather than silently becoming a default.
  public init?(urlToken: String) {
    switch urlToken {
    case "open": self = .`open`
    case "planned": self = .planned
    case "in-progress": self = .inProgress
    case "shipped": self = .shipped
    case "declined": self = .declined
    case "merged": self = .merged
    default: return nil
    }
  }
}
