import Foundation

// Emits, for every message, the names of its fields exactly as the schema spells them.
//
// A server reading `?cursor=` and a client writing it are both naming a field of a request message.
// Typed as a literal on either side that is a copy of the schema, and the copy is what drifts: a
// field renamed in the contract leaves a server still reading the old key and answering a default.
//
// So the names come from here. `DRListRequestsRequest.Field.cursor` is the same string the schema
// declares, and a field that no longer exists stops compiling rather than quietly never matching.
//
// A pure parser over the proto text, like the other generators here: protoc-gen-swift emits Swift
// property names, not wire names, and the wire name is what a query key has to be.

struct MessageFields {
  let name: String
  let fields: [String]
}

enum GeneratorError: Error, CustomStringConvertible {
  case usage
  case unreadable(String)

  var description: String {
    switch self {
    case .usage:
      return "usage: fields-gen <input.proto> <output-directory>"
    case .unreadable(let path):
      return "cannot read \(path)"
    }
  }
}

/// Field lines look like `string cursor = 4;` or `repeated DRRequestStatus statuses = 1;` or
/// `map<string, string> traits = 4;`. What is wanted is the name before the `=`.
func fieldName(from line: String) -> String? {
  guard let equalsIndex = line.firstIndex(of: "=") else { return nil }
  let declaration = line[..<equalsIndex].trimmingCharacters(in: .whitespaces)
  guard let name = declaration.split(separator: " ").last else { return nil }
  let candidate = String(name)
  // Anything that is not a plain identifier is not a field: `reserved 4`, `option ... `, nested
  // braces, and enum values (which are screaming snake case).
  guard candidate.allSatisfy({ $0.isLowercase || $0.isNumber || $0 == "_" }) else { return nil }
  return candidate
}

func parse(_ text: String) -> (prefix: String, messages: [MessageFields]) {
  var prefix = ""
  var messages: [MessageFields] = []

  var currentMessage: String?
  var currentFields: [String] = []

  for rawLine in text.split(separator: "\n", omittingEmptySubsequences: false) {
    let line = rawLine.trimmingCharacters(in: .whitespaces)

    if line.hasPrefix("option swift_prefix") {
      if let first = line.firstIndex(of: "\""), let last = line.lastIndex(of: "\""), first < last {
        prefix = String(line[line.index(after: first)..<last])
      }
      continue
    }

    if line.hasPrefix("message ") {
      currentMessage = line
        .dropFirst("message ".count)
        .trimmingCharacters(in: CharacterSet(charactersIn: " {}"))
      currentFields = []
      // A single-line empty message declares nothing.
      if line.hasSuffix("}") {
        currentMessage = nil
      }
      continue
    }

    guard currentMessage != nil else { continue }

    if line == "}" {
      if let name = currentMessage, currentFields.isEmpty == false {
        messages.append(MessageFields(name: name, fields: currentFields))
      }
      currentMessage = nil
      currentFields = []
      continue
    }

    if line.hasPrefix("//") || line.hasPrefix("reserved") || line.hasPrefix("option") {
      continue
    }
    if let name = fieldName(from: line) {
      currentFields.append(name)
    }
  }

  return (prefix, messages)
}

func lowerCamel(_ snake: String) -> String {
  let words = snake.split(separator: "_").map(String.init)
  guard let first = words.first else { return snake }
  return first + words.dropFirst().map { $0.capitalized }.joined()
}

func render(prefix: String, messages: [MessageFields], sourceFile: String) -> String {
  var out = """
    // DO NOT EDIT.
    //
    // Generated by fields-gen from \(sourceFile). Run Scripts/generate.sh.

    """

  for message in messages {
    out += """

      extension \(prefix)\(message.name) {
        /// This message's field names, as the schema spells them. What a query key or a form field
        /// has to be called.
        public enum Field {

      """
    for field in message.fields {
      out += "    public static let \(lowerCamel(field)) = \"\(field)\"\n"
    }
    out += """
        }
      }

      """
  }

  return out
}

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
  FileHandle.standardError.write(Data((GeneratorError.usage.description + "\n").utf8))
  exit(1)
}

do {
  guard let text = try? String(contentsOfFile: arguments[1], encoding: .utf8) else {
    throw GeneratorError.unreadable(arguments[1])
  }

  let sourceFile = (arguments[1] as NSString).lastPathComponent
  let parsed = parse(text)
  let rendered = render(prefix: parsed.prefix, messages: parsed.messages, sourceFile: sourceFile)

  let outputPath = (arguments[2] as NSString)
    .appendingPathComponent("Fields.\((sourceFile as NSString).deletingPathExtension).generated.swift")
  try rendered.write(toFile: outputPath, atomically: true, encoding: .utf8)
  print("fields-gen: wrote \(outputPath)")
} catch {
  FileHandle.standardError.write(Data(("fields-gen: \(error)\n").utf8))
  exit(1)
}
