import Foundation

/// One generated Swift file: the do-not-edit banner and every priced enum in it.
struct PriceFile {
  let sourceFileName: String
  let pricedEnums: [EmittedPricedEnum]

  var swiftSource: String {
    var out = """
      // DO NOT EDIT.
      //
      // Generated by price-gen from \(sourceFileName). Run Scripts/generate.sh.

      """
    for priced in pricedEnums {
      out += priced.swiftSource
    }
    return out
  }
}
